apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: falco
  namespace: falco

resources:
  - namespace.yaml
  - helmrelease.yaml
  - security-alerts.yaml
  - security-dashboard.yaml
