apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
  namespace: cloudflare-ddns
  labels:
    app.kubernetes.io/name: cloudflare-ddns
    app.kubernetes.io/part-of: infrastructure
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflare-ddns
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudflare-ddns
    spec:
      serviceAccountName: cloudflare-ddns
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: cloudflare-ddns
        image: favonia/cloudflare-ddns:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: CLOUDFLARE_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-api-token
              key: api-token
        - name: DOMAINS
          value: "lucena.cloud"
        - name: IP4_DOMAINS
          value: "lucena.cloud"
        - name: UPDATE_INTERVAL
          value: "5m"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: cloudflare-ddns
  namespace: cloudflare-ddns
  labels:
    app.kubernetes.io/name: cloudflare-ddns
    app.kubernetes.io/part-of: infrastructure
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: cloudflare-ddns
