apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cloudflare-ddns
  namespace: cloudflare-ddns

resources:
  - namespace.yaml
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: cloudflare-ddns
  app.kubernetes.io/part-of: infrastructure
