apiVersion: v1
kind: Namespace
metadata:
  name: cloudflare-ddns
  labels:
    name: cloudflare-ddns
    app.kubernetes.io/name: cloudflare-ddns
    app.kubernetes.io/part-of: infrastructure
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudflare-ddns
  namespace: cloudflare-ddns
  labels:
    app.kubernetes.io/name: cloudflare-ddns
    app.kubernetes.io/part-of: infrastructure
