---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  interval: 5m
  timeout: 15m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.13.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      replicaCount: 1
      nodeSelector:
        role: core
      resources:
        requests:
          cpu: 25m
          memory: 32Mi
        limits:
          cpu: 50m
          memory: 64Mi
      service:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/allow-shared-ip: nginx-ingress
          metallb.universe.tf/address-pool: first-pool
      config:
        use-proxy-protocol: "false"
        proxy-real-ip-cidr: "0.0.0.0/0"
        use-forwarded-headers: "true"
    defaultBackend:
      nodeSelector:
        role: core
      enabled: true
      resources:
        requests:
          cpu: 25m
          memory: 32Mi
        limits:
          cpu: 50m
          memory: 64Mi
    admissionWebhooks:
      enabled: true
      resources:
        requests:
          cpu: 25m
          memory: 32Mi
        limits:
          cpu: 50m
          memory: 64Mi

