---
# 🔍 Grafana Agent Operator HelmRelease
# 🎯 Provides CRDs required by Loki (PodLogs, etc.)
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-agent-operator
  namespace: grafana-agent-operator
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: grafana-agent-operator
      version: 0.4.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    # 🔧 Install CRDs (required for Loki)
    installCRDs: true
    
    # 🎯 Resource configuration
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    
    # 🔧 Node selector for observability nodes
    nodeSelector:
      role: observability
    
    # 🔧 Service configuration
    service:
      type: ClusterIP
    
    # 🔧 Replica configuration
    replicaCount: 1
