kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: homelab
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
    endpoint = ["http://kind-registry:5000"]
nodes:
- role: control-plane
  image: kindest/node:v1.34.0
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
- role: worker
  image: kindest/node:v1.34.0
  labels:
    role: homepage
- role: worker
  image: kindest/node:v1.34.0
  labels:
    role: worker
  extraPortMappings:
  - containerPort: 30000 # knative-lambda-mcp
    hostPort: 31000
    protocol: TCP
- role: worker
  image: kindest/node:v1.34.0
  labels:
    role: observability
  extraPortMappings: []
- role: worker
  image: kindest/node:v1.34.0
  labels:
    role: mcp-servers
  extraPortMappings:
  - containerPort: 30080 # grafana
    hostPort: 31080
    protocol: TCP
  - containerPort: 30090 # prometheus
    hostPort: 31090
    protocol: TCP
  - containerPort: 30100 # loki
    hostPort: 31100
    protocol: TCP
  - containerPort: 30110 # tempo
    hostPort: 31110
    protocol: TCP
  - containerPort: 30120 # jamie
    hostPort: 31120
    protocol: TCP
  - containerPort: 30130 # flux
    hostPort: 31130
    protocol: TCP
  - containerPort: 30140 # extra
    hostPort: 31140
    protocol: TCP
  - containerPort: 30150 # extra
    hostPort: 31150
    protocol: TCP
  - containerPort: 30160 # extra
    hostPort: 31160
    protocol: TCP