kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: homelab
nodes:
- role: control-plane
  image: kindest/node:v1.34.0
  extraPortMappings:
  - containerPort: 30080
    hostPort: 31080
    protocol: TCP
  - containerPort: 30090
    hostPort: 31090
    protocol: TCP
  - containerPort: 30100
    hostPort: 31100
    protocol: TCP
  - containerPort: 30443
    hostPort: 31443
    protocol: TCP
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
- role: worker
  image: kindest/node:v1.34.0
  labels:
    role: worker
- role: worker
  image: kindest/node:v1.34.0
  labels:
    role: worker
- role: worker
  image: kindest/node:v1.34.0
  labels:
    role: worker
- role: worker
  image: kindest/node:v1.34.0
  labels:
    role: observability
- role: worker
  image: kindest/node:v1.34.0
  labels:
    role: observability
- role: worker
  image: kindest/node:v1.34.0
  labels:
    role: observability
