apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-sre
  namespace: agent-sre
  labels:
    app.kubernetes.io/name: agent-sre
    app.kubernetes.io/component: sre-agent
    app.kubernetes.io/part-of: homelab
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: agent-sre
      app.kubernetes.io/component: sre-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: agent-sre
        app.kubernetes.io/component: sre-agent
        app.kubernetes.io/part-of: homelab
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: agent-sre
        image: ghcr.io/brunovlucena-org/agent-sre:latest
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: SERVICE_NAME
          value: "agent-sre"
        - name: HTTP_PORT
          value: "8080"
        - name: LOG_LEVEL
          value: "INFO"
        - name: LOGFIRE_TOKEN_SRE_AGENT
          valueFrom:
            secretKeyRef:
              name: ai-secrets
              key: LOGFIRE_TOKEN
        - name: LANGSMITH_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-secrets
              key: HF_TOKEN
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: config
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: agent-sre-config
      restartPolicy: Always
