apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-agent
  labels:
    app: sre-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sre-agent
  template:
    metadata:
      labels:
        app: sre-agent
    spec:
      containers:
      - name: sre-agent
        image: sre-agent:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 30120
          protocol: TCP
        env:
        - name: OLLAMA_URL
          value: "http://192.168.0.12:11434"
        - name: MODEL_NAME
          value: "bruno-sre:latest"
        - name: SERVICE_NAME
          value: "sre-agent"
        - name: SRE_API_KEY
          valueFrom:
            secretKeyRef:
              name: sre-agent-secret
              key: SRE_API_KEY
        - name: LOGFIRE_TOKEN_SRE_AGENT
          valueFrom:
            secretKeyRef:
              name: ai-secrets
              key: LOGFIRE_TOKEN_SRE_AGENT
        - name: LANGSMITH_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-secrets
              key: LANGSMITH_API_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 30120
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 30120
          initialDelaySeconds: 5
          periodSeconds: 5
