apiVersion: v1
kind: Namespace
metadata:
  name: agent-sre
  labels:
    name: agent-sre
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-agent-mcp
  namespace: agent-sre
  labels:
    app: sre-agent-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sre-agent-mcp
  template:
    metadata:
      labels:
        app: sre-agent-mcp
    spec:
      containers:
      - name: sre-agent-mcp
        image: ghcr.io/brunovlucena/agent-sre:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 30121
          name: http
        env:
        - name: MCP_PORT
          value: "30121"
        - name: MCP_HOST
          value: "0.0.0.0"
        - name: OLLAMA_URL
          value: "http://192.168.0.12:11434"
        - name: MODEL_NAME
          value: "bruno-sre:latest"
        - name: SERVICE_NAME
          value: "sre-agent"
        - name: LOGFIRE_TOKEN_SRE_AGENT
          valueFrom:
            secretKeyRef:
              name: ai-secrets
              key: LOGFIRE_TOKEN_SRE_AGENT
        - name: LANGSMITH_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-secrets
              key: LANGSMITH_API_KEY
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 30121
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 30121
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: sre-agent-mcp-service
  namespace: agent-sre
  labels:
    app: sre-agent-mcp
spec:
  type: NodePort
  ports:
  - port: 30121
    targetPort: 30121
    nodePort: 31121
    protocol: TCP
    name: http
  selector:
    app: sre-agent-mcp
