apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sre-agent-secret
  namespace: default
spec:
  encryptedData:
    SRE_API_KEY: AgCGvvKBfJK9qCjkuV8dFws9wxVK2CnoALvt/QWnU2qNtLTw41WDol+1e0VPx1pjkaaqDTVU14LTKksPuITHDTzNOdUzW9P8v+wTqHjQQJPBoaqMvEsir31B5UToJoy5ziCK3exEGqXJDXb2LuynIANgjmBW3T/mQcSZp/KQeOvOrVVxMQcdzSNUi69fR5UPd9iFWGoMCFiSBDmtRygyV6jX/3EorV0rJ1+bWxbeHN1BGtsFijf6z+kLSRsxg8EOIkolSuP0TKPqrkxlvDaqkM+LcRc9x5KoKw6kB1P/botMhoZJ7h/+CD7Ce22nKALWKeDbJFY+P8SYFiSBBCJNbkH4j1Gux9zcnIhmWuMjUwc1spa5nt9AW9ZPxdpheZXfBvD6B0p6xkr6/6jpqwp8dag3Cq9yPHDs4vOyM0FUtWOKs75T9UEAoe1SxUM2XOQaOHlNGCpugsV9Q2kv/54n/jc8yvAovaIXJQEoUHmjpMmiwlW4BFCfhb+VefYSfnFq7sUP4pe9ejHqqV2vzvr2z9naU3g+BkzMAJWq6tdSor/7h2Pjfhb5KVKgM0Ga7Tdz5PljZN7RqlRLoYZquUCz+VdX5RdBFOnJ+LpypphaigHtlxE3s6ocjIr8M1vO0/eTust9sXSxao9yi0qvdLUydhgpmEbPsaueyzpK9Z+PSDQkP/6ijnfW1WNTwi8XPZm+0p9NBYYSJXRNaRu1lxVDEBs=
  template:
    metadata:
      creationTimestamp: null
      name: sre-agent-secret
      namespace: default
---
