apiVersion: v1
kind: Service
metadata:
  name: agent-sre
  namespace: agent-sre
  labels:
    app.kubernetes.io/name: agent-sre
    app.kubernetes.io/component: sre-agent
    app.kubernetes.io/part-of: homelab
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: agent-sre
    app.kubernetes.io/component: sre-agent
