apiVersion: v1
kind: Service
metadata:
  name: sre-agent-service
  labels:
    app: sre-agent
spec:
  type: NodePort
  ports:
  - port: 30120
    targetPort: 30120
    nodePort: 31120
    protocol: TCP
  selector:
    app: sre-agent
