
apiVersion: v1
kind: Service
metadata:
  name: grafana-nodeport
  namespace: prometheus
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: prometheus-operator
    app.kubernetes.io/component: grafana
spec:
  type: NodePort
  ports:
  - name: aditional
    port: 80
    targetPort: 30003 # TODO: FIX IT!
    nodePort: 31080
    protocol: TCP
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: prometheus-operator
