
apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-config
  namespace: prometheus
  labels:
    app: mcp-config
data:
  mcp-config.json: |
    {
      "mcpServers": {
        "grafana": {
          "command": "npx",
          "args": ["@modelcontextprotocol/server-grafana"],
          "env": {
            "GRAFANA_URL": "http://prometheus-operator-grafana.prometheus.svc.cluster.local:80",
            "GRAFANA_API_KEY": "${GRAFANA_API_KEY}"
          }
        },
        "prometheus": {
          "command": "npx",
          "args": ["@modelcontextprotocol/server-prometheus"],
          "env": {
            "PROMETHEUS_URL": "http://prometheus-operator-kube-p-prometheus.prometheus.svc.cluster.local:9090"
          }
        }
      },
      "ollama": {
        "url": "http://192.168.0.3:11434",
        "model": "gemma3n:e4b"
      }
    }
