apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pagerduty-secrets
  namespace: prometheus
spec:
  encryptedData:
    pagerduty-service-key: AgCkHIhvl6EI4YLYvneLtqOpa6w3WXZN0jjj5utb0E84cbULYVqUJpyOHG90HODVKxcKyHuqvvxp5UJlCz9x2YTvm2coPYwJnzNjiQEzZVYpXYDHfWoHJgfBkuDqvBuG2YAua/GDgdTf1bozFo9cBsqwYEmFgNN6W9kpP67ljiNDhPQdDBwhCUKac2PNBcVdYbNB1DcG8js2xE63RFrrurrvhOuD8PoroeiYAEvzyehJ4BQ+Kp5XL3jfvJxxiwWDBbASvJB0vXXG1JusKJAjY8oGv/J+9lq+YETM8WMCjqV9zDCZIHtTGheTQMsxDVm4ka1tlNuvKRLaY2HWXUTrJ3al7iLjTOOrIKFW0wTjq7T2E3W6119BzYygQW/N15NOKy+T0hIthN7l9EQ+C/RW/IsJ8sACeFL7yFOPuMO3MQxZdqCmaWGLo/5AN9hTFfzH3s8IqSmop61sUhQ6weT1h0icbynCZfJStpqM69s2MxxM0021iEP+wgyOizQrm/6gRNPQP7NSM/syiU4FNBRdPLNEvfiER5nE96pucvYlbTXWt8XEYnzAooILB+YHPQ4nrr+YR+dGrPMIuHbXPIrrDBNuarHYtvH6hhlSQ5qWGOrLaDJJ+c4n7uFzI3mSwNdsBVklWtmtjsZ9BNalxP469V2+bFP8bVai4keVPOFk4yLCEI9AyfjFf6NUjhar+1o6LQPhomGmtkBvHrADaPqzttI9cM+n4Yea100NdP0N3OZ19g==
    slack-webhook-url: AgAHqFJwdlGOuvioHO0YlRw/13D5kGrKiSZJIriJTpiuAp/KzFgw3eAqyfWwlCRLsLeeoVBUauOviJMZWkwmeunfLDt72l8rsrqfVVCXPb+IaYubugAC/qxLhhC/K3tK0Mef+VaK9w1qyNAq/gnhZXCRgjUVqzB7OF1dOPEVXdgdjq9DqGPI72ajE4FHrgzYE0jNWwtGGRGY9ZLkIbx5tME4A5KGlIfYfsh6PRsfGfFmobm2RPMHvJ5huQ/nVRCZ3E1NbuSIIjUKEreH36c0GE21RjWf2ckifMrDzS0zPSFnNbtDF3yrD0sdrwd07/WxVIpHettdnOb2dQ+PcnmHDjagjBH4O0DYeICMuRlq8KqvoPddp5WYxEOafDBG3hVBC+aKN7gq7R6mIpM3ik1UVXreLTBfL/zkKkGiaJQ0EMVjsq84BUwEOQQzkZpaA6mEO1/qJCNsmCZ8OonAm86RSMJ8XGAB78jsZs41blpHRVS7we2nPTkZfDyzbDgeMCSXzp2C5vgOjTuIgN/VKGsAuHFuMatCMSQilmbxi3f45W//VCDC/WxDWwI2Jm6hpG9EFlRNxMhV/KReMLcRORa3yZ5aJcsvt47VXt1HLiX/ALv/qagrf2rMCEVZC9tXfSmdSycr+CpSJmGqUDodh+ao2Uad9EUPnllOYfF+W5AskFDh8tSqiIVRHidKrXAepMBqlk1fsEn4/Be4lSZAcxro2tSedtiuuzsc4IJsUjDG5fwScKYEjacuggh+9gUJrcL5CfhXANLJQKlPdTuQrUgCHtaI5mBRQ/kLb81ZXntnLqif1Hk=
  template:
    metadata:
      creationTimestamp: null
      name: pagerduty-secrets
      namespace: prometheus
    type: Opaque
---
