apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k6-operator
  namespace: k6-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: k6-operator
      version: '3.16.0'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    # k6-operator v3.16.0 configuration with flexible schema
    # Resource limits following your preference for low CPU allocation
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    
    # ServiceAccount configuration
    serviceAccount:
      create: true
    
    # RBAC configuration
    rbac:
      create: true
    
    # Prometheus monitoring
    serviceMonitor:
      enabled: true
