
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: loki
      version: 6.25.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    auth_enabled: false
    storage:
      type: s3
      s3:
        endpoint: minio.minio.svc:9000
        region: us-east-1
        bucket_name: loki
        access_key_id: admin
        secret_access_key: admin123
        s3forcepathstyle: true
        insecure: true
    loki:
      schemaConfig:
        configs:
          - from: "2020-10-24"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: index_
              period: 24h
      # Disable test schema since we have custom schemaConfig
      useTestSchema: false
      limits_config:
        retention_period: 744h
        allow_structured_metadata: false
    backend:
      replicas: 1
    read:
      replicas: 2
    write:
      replicas: 2
    monitoring:
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
    minio:
      enabled: true
      auth:
        rootUser: admin
        rootPassword: "admin123"
      persistence:
        enabled: true
        storageClassName: local-path
        size: 50Gi
      service:
        type: ClusterIP
    service:
      type: ClusterIP
    ingress:
      enabled: false

