# Default values for bruno-site
# This is a YAML-formatted file.

# Domain configuration
domain: "lucena.cloud"

replicaCount: 1

imagePullSecrets:
  - name: ghcr-secret
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

# API Configuration
api:
  image:
    repository: ghcr.io/brunovlucena/bruno-site/api
    pullPolicy: Always
    tag: "latest"
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# Ollama Configuration
ollama:
  url: "http://ollama.bruno.svc.cluster.local:11434"  # External Ollama server
  enabled: true

# Frontend Configuration
frontend:
  image:
    repository: ghcr.io/brunovlucena/bruno-site/frontend
    pullPolicy: Always
    tag: "latest"
  service:
    type: ClusterIP
    port: 80
  appEnv: "production"
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

ingress:
  enabled: false
  className: "nginx"
  hosts:
    - host: lucena.cloud

autoscaling:
  enabled: true
  minReplicas: 1 
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# CORS Configuration
corsOrigin: "https://lucena.cloud"

# Database configuration
database:
  enabled: true
  type: postgresql
  host: homepage-bruno-site-postgres
  port: 5432
  name: bruno_site
  user: postgres
  password: ""
  existingSecret: "bruno-site-db-secret"  # Created by Sealed Secrets

# PostgreSQL configuration
postgres:
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  persistence:
    enabled: true
    size: 8Gi
    storageClass: ""

# Redis configuration
redis:
  enabled: true
  host: homepage-bruno-site-redis
  port: 6379
  password: "enabled"  # Set to "enabled" to use the secret
  existingSecret: "bruno-site-redis-secret"  # Created by Sealed Secrets
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  persistence:
    enabled: true
    size: 2Gi
    storageClass: ""

# Secrets - These should be provided via external secret management
# DO NOT set actual passwords here - use Kubernetes secrets instead
secrets:
  databasePassword: ""  # Set via Kubernetes secret
  redisPassword: ""     # Set via Kubernetes secret

# K6 Load Testing Configuration
k6:
  enabled: true  # Set to true to enable load testing
  parallelism: 1
  arguments: "--out json=results.json --tag test_type=bruno-site --tag scenario=api_load_test"
  runner:
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi

# Monitoring Configuration
monitoring:
  enabled: true
  prometheus:
    enabled: true
    rules:
      enabled: true
    servicemonitor:
      enabled: true
  grafana:
    enabled: true
    dashboard:
      enabled: true
  alertmanager:
    enabled: true
    webhook:
      url: ""  # Set your webhook URL for notifications
    email:
      smtp_host: "localhost"
      smtp_port: 587
      from: "alerts@bruno-site.com"
      to: "sre-team@bruno-site.com"
    slack:
      webhook_url: ""  # Set your Slack webhook URL
      channel: "#bruno-site-alerts"
      icon_emoji: ":bruno-slack:"  # Custom Bruno Slack icon
      icon_url: "https://lucena.cloud/assets/logos/bruno-slack-logo.png"  # Direct link to PNG icon
  
  # Metrics configuration
  metrics:
    enabled: true
    path: /metrics
    port: 8080
    interval: 30s
    timeout: 10s
    basicAuth:
      enabled: false
      username: "admin"
      password: ""  # Set via secret
  
  # Environment and cluster labels
  environment: "production"
  cluster: "default"
  team: "sre"
  application: "bruno-site"
