apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: twingate-connector
  namespace: twingate
spec:
  interval: 5m
  timeout: 15m
  chart:
    spec:
      chart: connector
      version: ">=1.0.0"
      sourceRef:
        kind: HelmRepository
        name: twingate
        namespace: flux-system
  values:
    connector:
      network: "bvlucena"
      existingSecret: "twingate-credentials"
