---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actions-runner-controller
  namespace: action-runners
spec:
  interval: 5m
  chart:
    spec:
      chart: actions-runner-controller
      version: 0.23.7
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
  values:
    # GitHub configuration
    githubConfigSecret: github-config
    
    # Controller configuration
    controllerReplicaCount: 1
    
    # Runner configuration
    runnerReplicaCount: 2
    runnerImage: summerwind/actions-runner:latest
    
    # Service account configuration
    serviceAccount:
      create: true
      annotations: {}
    
    # RBAC configuration
    rbac:
      create: true
    
    # Metrics configuration
    metrics:
      enabled: false
    
    # Secret configuration
    authSecret:
      create: true
      name: controller-manager
