apiVersion: v1
kind: Namespace
metadata:
  name: grafana-mcp
  labels:
    name: grafana-mcp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-mcp-server
  namespace: grafana-mcp
  labels:
    app: grafana-mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-mcp-server
  template:
    metadata:
      labels:
        app: grafana-mcp-server
    spec:
      containers:
      - name: grafana-mcp-server
        image: mcp/grafana:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: GRAFANA_URL
          value: "https://grafana.lucena.cloud"
        - name: GRAFANA_API_KEY
          valueFrom:
            secretKeyRef:
              name: grafana-mcp-secrets
              key: GRAFANA_API_KEY
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-mcp-service
  namespace: grafana-mcp
  labels:
    app: grafana-mcp-server
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30122
    protocol: TCP
    name: http
  selector:
    app: grafana-mcp-server
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-mcp-secrets
  namespace: grafana-mcp
type: Opaque
stringData:
  GRAFANA_API_KEY: "GLSA_LyBkhKFTGoCxmQXAcMNLZDOfc8SSVMmf_4671bfea"
