apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - k8s-all.yaml

namespace: grafana-mcp

commonLabels:
  app.kubernetes.io/name: grafana-mcp
  app.kubernetes.io/instance: grafana-mcp
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/component: mcp-server
  app.kubernetes.io/part-of: homelab
