apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-control-plane
  namespace: linkerd
spec:
  interval: 5m
  chart:
    spec:
      chart: linkerd-control-plane
      version: "1.15.0"
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
  values:
    # Linkerd control plane configuration
    controllerImage: cr.l5d.io/linkerd/controller
    debugContainer:
      image:
        name: cr.l5d.io/linkerd/debug
    destinationResources:
      requests:
        cpu: 10m
        memory: 20Mi
    destinationProxyResources:
      requests:
        cpu: 10m
        memory: 20Mi
    identityResources:
      requests:
        cpu: 10m
        memory: 20Mi
    identityProxyResources:
      requests:
        cpu: 10m
        memory: 20Mi
    proxyInjectorResources:
      requests:
        cpu: 10m
        memory: 20Mi
    proxyInjectorProxyResources:
      requests:
        cpu: 10m
        memory: 20Mi
    spValidatorResources:
      requests:
        cpu: 10m
        memory: 20Mi
    spValidatorProxyResources:
      requests:
        cpu: 10m
        memory: 20Mi
    tapResources:
      requests:
        cpu: 10m
        memory: 20Mi
    tapProxyResources:
      requests:
        cpu: 10m
        memory: 20Mi
    # Disable automatic trust anchor generation for now
    # This will be handled by the Linkerd CLI
    identity:
      issuer:
        scheme: kubernetes.io/tls