apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-control-plane
  namespace: linkerd
spec:
  interval: 5m
  chart:
    spec:
      chart: linkerd-control-plane
      version: "1.15.0"
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
  values:
    # Linkerd control plane configuration
    controllerImage: cr.l5d.io/linkerd/controller
    debugContainer:
      image:
        name: cr.l5d.io/linkerd/debug
    destinationResources:
      requests:
        cpu: 10m
        memory: 20Mi
    destinationProxyResources:
      requests:
        cpu: 10m
        memory: 20Mi
    identityResources:
      requests:
        cpu: 10m
        memory: 20Mi
    identityProxyResources:
      requests:
        cpu: 10m
        memory: 20Mi
    policyResources:
      requests:
        cpu: 10m
        memory: 20Mi
    policyProxyResources:
      requests:
        cpu: 10m
        memory: 20Mi
    proxyInjectorResources:
      requests:
        cpu: 10m
        memory: 20Mi
    spValidatorResources:
      requests:
        cpu: 10m
        memory: 20Mi
    # Enable high availability
    highAvailability: false
    # Configure proxy settings
    proxy:
      image:
        name: cr.l5d.io/linkerd/proxy
      resources:
        cpu:
          limit: 100m
          request: 10m
        memory:
          limit: 250Mi
          request: 20Mi
    # Configure identity settings
    identity:
      issuer:
        scheme: kubernetes.io/tls
    # Configure policy
    policy:
      enabled: true
    # Configure destination
    destination:
      enabled: true
    # Configure proxy injector
    proxyInjector:
      enabled: true
    # Configure service profile validator
    spValidator:
      enabled: true
    # Configure heartbeat
    heartbeat:
      enabled: true
    # Configure tap
    tap:
      enabled: true
    # Configure dashboard
    dashboard:
      enabled: true
      replicas: 1
    # Configure Grafana
    grafana:
      enabled: true
      replicas: 1
    # Configure Prometheus
    prometheus:
      enabled: true
      replicas: 1
    # Configure webhook
    webhook:
      enabled: true
    # Configure debug
    debug:
      enabled: true
