apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-crds
  namespace: linkerd
spec:
  interval: 5m
  chart:
    spec:
      chart: linkerd-enterprise-crds
      version: "2.18.0"
      sourceRef:
        kind: HelmRepository
        name: buoyant
        namespace: flux-system
  values:
    installGatewayAPI: false
