apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-viz
  namespace: linkerd
spec:
  interval: 5m
  chart:
    spec:
      chart: linkerd-viz
      version: "1.14.0"
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
  values:
    # Linkerd Viz configuration for observability
    grafana:
      enabled: true
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    prometheus:
      enabled: true
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    tap:
      enabled: true
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    tapInjector:
      enabled: true
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    web:
      enabled: true
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    # Configure dashboard
    dashboard:
      enabled: true
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    # Configure metrics API
    metricsAPI:
      enabled: true
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    # Configure Prometheus configuration
    prometheusConfig:
      enabled: true
    # Configure Grafana configuration
    grafanaConfig:
      enabled: true
    # Configure dashboard configuration
    dashboardConfig:
      enabled: true
