apiVersion: v1
kind: Service
metadata:
  name: langgraph-agent
  namespace: langgraph-agent
  labels:
    app.kubernetes.io/name: langgraph-agent
    app.kubernetes.io/component: ai-agent
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/name: langgraph-agent
    app.kubernetes.io/component: ai-agent
