---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: bruno
spec:
  interval: 5m
  chart:
    spec:
      chart: ./chart
      version: 0.1.9
      sourceRef:
        kind: GitRepository
        name: bruno-site
        namespace: flux-system
  values:
    ingress:
      enabled: false
    monitoring:
      enabled: true