
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bruno-site.fullname" . }}-frontend-nodeport
  labels:
    {{- include "bruno-site.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
    app.kubernetes.io/name: bruno-site-frontend-nodeport
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 30120
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: metrics
    nodePort: 30121
    protocol: TCP
  selector:
    {{- include "bruno-site.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
