apiVersion: v1
kind: Service
metadata:
  name: {{ include "bruno-site.fullname" . }}-frontend
  labels:
    {{- include "bruno-site.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.domain }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "bruno-site.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend