apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: bruno-site-rules
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: bruno-site
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: monitoring
    prometheus: kube-prometheus
    role: alert-rules
spec:
  groups:
  # =============================================================================
  # 🚨 CRITICAL ALERTS - IMMEDIATE ATTENTION REQUIRED
  # =============================================================================
  - name: bruno-site.critical
    rules:
    - alert: BrunoSiteAPIDown
      expr: up{job="bruno-site-api"} == 0
      for: 1m
      labels:
        severity: critical
        service: api
        component: bruno-site
      annotations:
        summary: "Bruno Site API is down"
        description: "Bruno Site API has been down for more than 1 minute. This affects all site functionality."
        runbook_url: "https://github.com/brunovlucena/bruno-site/docs/runbooks/api-down.md"
        
    - alert: BrunoSiteDatabaseDown
      expr: up{job="bruno-site-postgres"} == 0
      for: 1m
      labels:
        severity: critical
        service: database
        component: bruno-site
      annotations:
        summary: "Bruno Site Database is down"
        description: "PostgreSQL database has been down for more than 1 minute. All data operations are failing."
        runbook_url: "https://github.com/brunovlucena/bruno-site/docs/runbooks/database-down.md"
        
    - alert: BrunoSiteRedisDown
      expr: up{job="bruno-site-redis"} == 0
      for: 2m
      labels:
        severity: critical
        service: redis
        component: bruno-site
      annotations:
        summary: "Bruno Site Redis is down"
        description: "Redis cache has been down for more than 2 minutes. Session management and caching are affected."
        runbook_url: "https://github.com/brunovlucena/bruno-site/docs/runbooks/redis-down.md"

    - alert: BrunoSiteHighErrorRate
      expr: rate(http_requests_total{job="bruno-site-api",code=~"5.."}[5m]) / rate(http_requests_total{job="bruno-site-api"}[5m]) > 0.05
      for: 2m
      labels:
        severity: critical
        service: api
        component: bruno-site
      annotations:
        summary: "Bruno Site API high error rate"
        description: "Bruno Site API error rate is {{`{{ $value }}`}} for the last 5 minutes."
        runbook_url: "https://github.com/brunovlucena/bruno-site/docs/runbooks/high-error-rate.md"

    - alert: BrunoSiteDatabaseConnectionFailure
      expr: increase(pg_stat_database_deadlocks{job="bruno-site-postgres"}[5m]) > 10
      for: 1m
      labels:
        severity: critical
        service: database
        component: bruno-site
      annotations:
        summary: "Bruno Site Database connection issues"
        description: "PostgreSQL database has {{`{{ $value }}`}} deadlocks in the last 5 minutes."
        runbook_url: "https://github.com/brunovlucena/bruno-site/docs/runbooks/database-connection-issues.md"

  # =============================================================================
  # ⚠️ WARNING ALERTS - ATTENTION NEEDED SOON
  # =============================================================================
  - name: bruno-site.warning
    rules:
    - alert: BrunoSiteHighResponseTime
      expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="bruno-site-api"}[5m])) > 1
      for: 5m
      labels:
        severity: warning
        service: api
        component: bruno-site
      annotations:
        summary: "Bruno Site API high response time"
        description: "Bruno Site API 95th percentile response time is {{`{{ $value }}`}}s for the last 5 minutes."
        runbook_url: "https://github.com/brunovlucena/bruno-site/docs/runbooks/high-response-time.md"

    - alert: BrunoSiteHighCPUUsage
      expr: rate(container_cpu_usage_seconds_total{pod=~"bruno-site-api-.*"}[5m]) > 0.8
      for: 5m
      labels:
        severity: warning
        service: api
        component: bruno-site
      annotations:
        summary: "Bruno Site API high CPU usage"
        description: "Bruno Site API CPU usage is {{`{{ $value }}`}} for the last 5 minutes."
        runbook_url: "https://github.com/brunovlucena/bruno-site/docs/runbooks/high-cpu-usage.md"

    - alert: BrunoSiteHighMemoryUsage
      expr: container_memory_usage_bytes{pod=~"bruno-site-api-.*"} / container_spec_memory_limit_bytes{pod=~"bruno-site-api-.*"} > 0.9
      for: 5m
      labels:
        severity: warning
        service: api
        component: bruno-site
      annotations:
        summary: "Bruno Site API high memory usage"
        description: "Bruno Site API memory usage is {{`{{ $value }}`}} of limit for the last 5 minutes."
        runbook_url: "https://github.com/brunovlucena/bruno-site/docs/runbooks/high-memory-usage.md"

    - alert: BrunoSiteDatabaseSlowQueries
      expr: rate(pg_stat_database_tup_returned{job="bruno-site-postgres"}[5m]) / rate(pg_stat_database_tup_fetched{job="bruno-site-postgres"}[5m]) < 0.1
      for: 10m
      labels:
        severity: warning
        service: database
        component: bruno-site
      annotations:
        summary: "Bruno Site Database slow queries detected"
        description: "PostgreSQL database shows inefficient query patterns with low tuple return ratio."
        runbook_url: "https://github.com/brunovlucena/bruno-site/docs/runbooks/database-slow-queries.md"

    - alert: BrunoSiteRedisHighMemoryUsage
      expr: redis_memory_used_bytes{job="bruno-site-redis"} / redis_config_maxmemory_bytes{job="bruno-site-redis"} > 0.8
      for: 5m
      labels:
        severity: warning
        service: redis
        component: bruno-site
      annotations:
        summary: "Bruno Site Redis high memory usage"
        description: "Redis memory usage is {{`{{ $value }}`}} of max memory for the last 5 minutes."
        runbook_url: "https://github.com/brunovlucena/bruno-site/docs/runbooks/redis-high-memory.md"

    - alert: BrunoSiteLLMServiceDown
      expr: up{job="bruno-site-ollama"} == 0
      for: 5m
      labels:
        severity: warning
        service: llm
        component: bruno-site
      annotations:
        summary: "Bruno Site LLM service is down"
        description: "Ollama LLM service has been down for more than 5 minutes. AI chat functionality is affected."
        runbook_url: "https://github.com/brunovlucena/bruno-site/docs/runbooks/llm-service-down.md"

  # =============================================================================
  # 📊 BUSINESS LOGIC ALERTS - APPLICATION SPECIFIC
  # =============================================================================
  - name: bruno-site.business
    rules:
    - alert: BrunoSiteHighProjectViewErrors
      expr: rate(http_requests_total{job="bruno-site-api",handler="/api/projects",code=~"4..|5.."}[10m]) > 0.1
      for: 5m
      labels:
        severity: warning
        service: api
        component: bruno-site
        feature: projects
      annotations:
        summary: "Bruno Site high project view errors"
        description: "Project viewing functionality has {{`{{ $value }}`}} errors per second for the last 10 minutes."
        runbook_url: "https://github.com/brunovlucena/bruno-site/docs/runbooks/project-errors.md"

    - alert: BrunoSiteChatAPIErrors
      expr: rate(http_requests_total{job="bruno-site-api",handler="/api/chat",code=~"4..|5.."}[10m]) > 0.05
      for: 5m
      labels:
        severity: warning
        service: api
        component: bruno-site
        feature: chat
      annotations:
        summary: "Bruno Site chat API errors"
        description: "AI chat functionality has {{`{{ $value }}`}} errors per second for the last 10 minutes."
        runbook_url: "https://github.com/brunovlucena/bruno-site/docs/runbooks/chat-errors.md"

    - alert: BrunoSiteHighAnalyticsLoad
      expr: rate(http_requests_total{job="bruno-site-api",handler="/api/analytics/track"}[5m]) > 10
      for: 10m
      labels:
        severity: info
        service: api
        component: bruno-site
        feature: analytics
      annotations:
        summary: "Bruno Site high analytics load"
        description: "Analytics tracking is receiving {{`{{ $value }}`}} requests per second for the last 5 minutes."
        runbook_url: "https://github.com/brunovlucena/bruno-site/docs/runbooks/high-analytics-load.md"

  # =============================================================================
  # 🔧 INFRASTRUCTURE ALERTS - KUBERNETES & RESOURCES
  # =============================================================================
  - name: bruno-site.infrastructure
    rules:
    - alert: BrunoSitePodCrashLooping
      expr: rate(kube_pod_container_status_restarts_total{pod=~"bruno-site-.*"}[15m]) > 0
      for: 5m
      labels:
        severity: critical
        service: kubernetes
        component: bruno-site
      annotations:
        summary: "Bruno Site pod is crash looping"
        description: "Pod {{`{{ $labels.pod }}`}} in namespace {{`{{ $labels.namespace }}`}} is crash looping with {{`{{ $value }}`}} restarts in the last 15 minutes."
        runbook_url: "https://github.com/brunovlucena/bruno-site/docs/runbooks/pod-crash-loop.md"

    - alert: BrunoSitePodNotReady
      expr: kube_pod_status_phase{pod=~"bruno-site-.*",phase!="Running"} == 1
      for: 5m
      labels:
        severity: warning
        service: kubernetes
        component: bruno-site
      annotations:
        summary: "Bruno Site pod is not ready"
        description: "Pod {{`{{ $labels.pod }}`}} in namespace {{`{{ $labels.namespace }}`}} is in {{`{{ $labels.phase }}`}} state for more than 5 minutes."
        runbook_url: "https://github.com/brunovlucena/bruno-site/docs/runbooks/pod-not-ready.md"

    - alert: BrunoSiteHPAHighReplicas
      expr: kube_horizontalpodautoscaler_status_current_replicas{horizontalpodautoscaler=~"bruno-site-.*"} > 8
      for: 10m
      labels:
        severity: warning
        service: kubernetes
        component: bruno-site
      annotations:
        summary: "Bruno Site HPA scaling to high replica count"
        description: "HPA {{`{{ $labels.horizontalpodautoscaler }}`}} has scaled to {{`{{ $value }}`}} replicas for more than 10 minutes."
        runbook_url: "https://github.com/brunovlucena/bruno-site/docs/runbooks/hpa-high-replicas.md"

    - alert: BrunoSiteStorageSpaceLow
      expr: (kubelet_volume_stats_available_bytes{pod=~"bruno-site-.*"} / kubelet_volume_stats_capacity_bytes{pod=~"bruno-site-.*"}) < 0.1
      for: 5m
      labels:
        severity: warning
        service: storage
        component: bruno-site
      annotations:
        summary: "Bruno Site storage space is low"
        description: "Pod {{`{{ $labels.pod }}`}} has only {{`{{ $value }}`}} storage space remaining."
        runbook_url: "https://github.com/brunovlucena/bruno-site/docs/runbooks/storage-space-low.md"

  # =============================================================================
  # 🔒 SECURITY ALERTS - SECURITY MONITORING
  # =============================================================================
  - name: bruno-site.security
    rules:
    - alert: BrunoSiteHighRateLimitHits
      expr: rate(http_requests_total{job="bruno-site-api",code="429"}[5m]) > 0.1
      for: 5m
      labels:
        severity: warning
        service: api
        component: bruno-site
        security: rate-limiting
      annotations:
        summary: "Bruno Site high rate limit hits"
        description: "Bruno Site API is hitting rate limits with {{`{{ $value }}`}} requests per second for the last 5 minutes."
        runbook_url: "https://github.com/brunovlucena/bruno-site/docs/runbooks/rate-limit-hits.md"

    - alert: BrunoSiteSuspiciousActivity
      expr: rate(http_requests_total{job="bruno-site-api",code=~"4.."}[5m]) > 5
      for: 10m
      labels:
        severity: warning
        service: api
        component: bruno-site
        security: suspicious-activity
      annotations:
        summary: "Bruno Site suspicious activity detected"
        description: "Bruno Site API is receiving {{`{{ $value }}`}} 4xx errors per second for the last 5 minutes, indicating potential suspicious activity."
        runbook_url: "https://github.com/brunovlucena/bruno-site/docs/runbooks/suspicious-activity.md"

    - alert: BrunoSiteSQLInjectionAttempts
      expr: increase(http_requests_total{job="bruno-site-api",handler="/api",code="400"}[10m]) > 20
      for: 5m
      labels:
        severity: warning
        service: api
        component: bruno-site
        security: sql-injection
      annotations:
        summary: "Bruno Site potential SQL injection attempts"
        description: "Bruno Site API has received {{`{{ $value }}`}} 400 errors in the last 10 minutes, potentially indicating SQL injection attempts."
        runbook_url: "https://github.com/brunovlucena/bruno-site/docs/runbooks/sql-injection-attempts.md"

  # =============================================================================
  # 📈 PERFORMANCE ALERTS - PERFORMANCE MONITORING
  # =============================================================================
  - name: bruno-site.performance
    rules:
    - alert: BrunoSiteSlowDatabaseQueries
      expr: histogram_quantile(0.95, rate(pg_stat_database_tup_fetched{job="bruno-site-postgres"}[5m])) > 1000
      for: 10m
      labels:
        severity: warning
        service: database
        component: bruno-site
        performance: slow-queries
      annotations:
        summary: "Bruno Site slow database queries"
        description: "PostgreSQL database 95th percentile query performance is {{`{{ $value }}`}} tuples fetched per second for the last 5 minutes."
        runbook_url: "https://github.com/brunovlucena/bruno-site/docs/runbooks/slow-database-queries.md"

    - alert: BrunoSiteHighConnectionPoolUsage
      expr: pg_stat_database_numbackends{job="bruno-site-postgres"} / pg_settings_max_connections{job="bruno-site-postgres"} > 0.8
      for: 5m
      labels:
        severity: warning
        service: database
        component: bruno-site
        performance: connection-pool
      annotations:
        summary: "Bruno Site high database connection pool usage"
        description: "PostgreSQL connection pool usage is {{`{{ $value }}`}} for the last 5 minutes."
        runbook_url: "https://github.com/brunovlucena/bruno-site/docs/runbooks/high-connection-pool-usage.md"

    - alert: BrunoSiteRedisSlowOperations
      expr: rate(redis_commands_duration_seconds_total{job="bruno-site-redis"}[5m]) > 0.1
      for: 5m
      labels:
        severity: warning
        service: redis
        component: bruno-site
        performance: slow-operations
      annotations:
        summary: "Bruno Site Redis slow operations"
        description: "Redis operations are taking {{`{{ $value }}`}} seconds on average for the last 5 minutes."
        runbook_url: "https://github.com/brunovlucena/bruno-site/docs/runbooks/redis-slow-operations.md"

  # =============================================================================
  # 🎯 AVAILABILITY ALERTS - UPTIME MONITORING
  # =============================================================================
  - name: bruno-site.availability
    rules:
    - alert: BrunoSiteLowAvailability
      expr: (rate(http_requests_total{job="bruno-site-api",code=~"2.."}[1h]) / rate(http_requests_total{job="bruno-site-api"}[1h])) < 0.99
      for: 15m
      labels:
        severity: critical
        service: api
        component: bruno-site
        availability: uptime
      annotations:
        summary: "Bruno Site low availability"
        description: "Bruno Site API availability is {{`{{ $value }}`}} for the last hour, below 99% threshold."
        runbook_url: "https://github.com/brunovlucena/bruno-site/docs/runbooks/low-availability.md"

    - alert: BrunoSiteHealthCheckFailures
      expr: rate(http_requests_total{job="bruno-site-api",handler="/health",code!="200"}[5m]) > 0
      for: 2m
      labels:
        severity: critical
        service: api
        component: bruno-site
        availability: health-checks
      annotations:
        summary: "Bruno Site health check failures"
        description: "Bruno Site API health checks are failing with {{`{{ $value }}`}} failures per second for the last 5 minutes."
        runbook_url: "https://github.com/brunovlucena/bruno-site/docs/runbooks/health-check-failures.md"
