{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bruno-site.fullname" . }}-redis
  labels:
    {{- include "bruno-site.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
    - port: 9121
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "bruno-site.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
