{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bruno-site.fullname" . }}-redis
  labels:
    {{- include "bruno-site.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "bruno-site.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "bruno-site.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: redis:7.2-alpine
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          # {{- if .Values.redis.password }}
          # env:
          #   - name: REDIS_PASSWORD
          #     {{- if .Values.redis.existingSecret }}
          #     valueFrom:
          #       secretKeyRef:
          #         name: {{ .Values.redis.existingSecret }}
          #         key: password
          #     {{- else }}
          #     value: {{ .Values.redis.password | quote }}
          #     {{- end }}
          # command:
          #   - redis-server
          #   - --requirepass
          #   - $(REDIS_PASSWORD)
          # {{- end }}
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: redis-storage
              mountPath: /data
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
      volumes:
        - name: redis-storage
          {{- if .Values.redis.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "bruno-site.fullname" . }}-redis-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end }}
