apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: flagger-infrastructure
  namespace: flagger-system

resources:
  - namespace.yaml
  - helmrelease.yaml
  - gateway.yaml
