---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: tempo
spec:
  interval: 5m
  chart:
    spec:
      chart: tempo
      version: 1.23.3
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    tempo:
      # Configure Tempo container port
      server:
        http_listen_port: 3200
        grpc_listen_port: 9095
      # Storage configuration for local development
      storage:
        trace:
          backend: local
          local:
            path: /tmp/tempo/traces
      retention: 24h
      metrics_generator:
        enabled: true
        storage:
          path: /tmp/tempo/generator/wal
          remote_write:
            - url: http://prometheus-operated.prometheus:9090/api/v1/write
              send_exemplars: true
      # Configure distributor for OTLP ingestion
      distributor:
        receivers:
          otlp:
            protocols:
              grpc:
                endpoint: 0.0.0.0:4317
              http:
                endpoint: 0.0.0.0:4318
    # Configure NodePort service for Tempo UI
    service:
      type: NodePort
      port: 3200
      nodePort: 3200
    # Additional services for distributor
    distributor:
      service:
        type: ClusterIP
        ports:
          - name: otlp-grpc
            port: 4317
            targetPort: 4317
          - name: otlp-http
            port: 4318
            targetPort: 4318
    # Disable ingress since we're using NodePort
    ingress:
      enabled: false
    # Configure resources for homelab environment
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    # Persistence for local storage
    persistence:
      enabled: true
      storageClassName: standard
      size: 10Gi
