apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: homelab
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/brunovlucena/homelab.git
  ref:
    branch: main