apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cloudflare-tunnel
  namespace: flux-system

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - prometheus-rule.yaml
  - servicemonitor.yaml
  - canary-monitoring.yaml