apiVersion: v1
kind: Namespace
metadata:
  name: cloudflare-tunnel
  labels:
    name: cloudflare-tunnel
    app.kubernetes.io/name: cloudflare-tunnel
    app.kubernetes.io/component: networking
    app.kubernetes.io/part-of: home-infrastructure
