apiVersion: v1
kind: Service
metadata:
  name: cloudflared-metrics
  namespace: cloudflare-tunnel
  labels:
    app.kubernetes.io/name: cloudflare-tunnel
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: home-infrastructure
spec:
  type: ClusterIP
  selector:
    app: cloudflared
  ports:
    - name: metrics
      port: 2000
      targetPort: 2000
      protocol: TCP
