---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 5m
  chart:
    spec:
      chart: loki-simple-scalable
      version: 1.8.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    loki:
      auth_enabled: false
      storage:
        type: s3
        s3:
          endpoint: minio.minio.svc:9000
          region: us-east-1
          bucket_name: loki
          access_key_id: admin
          secret_access_key: admin123
          s3forcepathstyle: true
          insecure: true
      retention_deletes_enabled: true
      retention_period: 744h
      table_manager:
        retention_deletes_enabled: true
        retention_period: 744h
    minio:
      enabled: true
      auth:
        rootUser: admin
        rootPassword: "admin123"
      persistence:
        enabled: true
        storageClassName: local-path
        size: 50Gi
      service:
        type: ClusterIP
    resources:
      requests:
        cpu: 250m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 4Gi
    service:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: loki.dev.local
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: loki-tls
          hosts:
            - loki.dev.local

