---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus-mcp
  labels:
    name: prometheus-mcp
    app.kubernetes.io/name: prometheus-mcp
    app.kubernetes.io/instance: prometheus-mcp
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: mcp-server
    app.kubernetes.io/part-of: observability
