---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: tempo
spec:
  interval: 5m
  chart:
    spec:
      chart: tempo
      version: 1.23.3
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    tempo:
      storage:
        trace:
          backend: s3
          s3:
            endpoint: minio.minio.svc:9000
            region: us-east-1
            bucket: tempo
            accessKey: admin
            secretKey: admin123
            forcePathStyle: true
            insecure: true
      retention: 24h
      metrics_generator:
        enabled: false
    minio:
      enabled: true
      auth:
        rootUser: admin
        rootPassword: "admin123"
      persistence:
        enabled: true
        storageClassName: standard
        size: 50Gi
      service:
        type: ClusterIP
    service:
      type: ClusterIP
    ingress:
      enabled: false
