---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq-operator
  namespace: rabbitmq-operator
spec:
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: rabbitmq-cluster-operator
      version: 4.3.24
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    createNamespace: true
  values:
    # Based on notifi configuration
    useCertManager: true
    
    # Tolerations for node scheduling (matching notifi setup)
    # tolerations:
    #   - key: "knative"
    #     operator: Equal
    #     value: "true"
    #     effect: NoSchedule
    
    # Cluster operator configuration
    clusterOperator:
      # Resource allocation similar to notifi (low CPU as per user preference)
      # resources:
      #   requests:
      #     cpu: 100m
      #     memory: 100Mi
      #   limits:
      #     cpu: 1000m
      #     memory: 1000Mi
      
      # Metrics configuration (matching notifi setup)
      metrics:
        service:
          enabled: true
        serviceMonitor:
          enabled: true
      
      # Security context
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
