apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bruno-site-db-secret
  namespace: bruno
spec:
  encryptedData:
    password: AgBGpQU7pqZrtTU+FeDW3U/nGNgtP4h93tqRyGTgdUkWWzzrcI0YAj1VZm6r1zg8bji1q70aQPZhsXktDtsWJzflySvl/tqbG1Rlz9sjdZpDIaRav1uymNdw4hnH1w9X4DpEq4ffcwwwJm62DwvFKBv9y8cAhxuCVkfYPyqj25T3269SknzjbkIxm67S8wecpncDzkcGqG51LHYoa1DaywAHumbknpWXrtUDqGXPN2LW/+kvBnlQM9RlWHi3aRh3HXilZsKtoA6laGeJtl96AIRsGIKuHO4VwEofRVQQsTTzYOlrQsINI1cWnnrzjauh7Ttyed0gWu9X+3hlWAPzwadW7n/KhyvrGgdy5Sls2vl2WPVpkT1uGI6GMl80BjyxgIG1ETJ4MFqZd5SMb4tKSfj1+aYPytJQ/33/ZIX5+fFqvyPcpamPSf5WBnghk3zutD7P0l7rGH8NcdzEbQ+UXgeAzsB+fO8+rHRoOJFoiJ0LEsSXxb3f1zZHXeA5yiVzk6WANTnehW49PJ/UtqC8BesnWwfz9wddck4d25WGzyM1vQwGy2xqx7etsIRHEQIEqQcwPx9I1wNvxiFadabAdXEUjkcCoXJ+RA5gcRJOVM1VeotkA9eOakHmJsKiwN3bB1HGBl1CJpF/gJdFfK8dr6af30XrFeecZ7jCaFHq9XqTXEC/1Wcc89kk3+L8QLudEkk5Kjl9IM+h+ftwrEgJ6Yp7hm5J3pUg6HvzPIIADiRmRFcuSQdoQ0jqJsvwKw==
  template:
    metadata:
      creationTimestamp: null
      name: bruno-site-db-secret
      namespace: bruno
    type: Opaque
---
