apiVersion: v1
kind: Secret
metadata:
  name: jamie-sre-chatbot-secrets
  namespace: chatbots
  labels:
    app: jamie-sre-chatbot
    app.kubernetes.io/name: jamie-sre-chatbot
    app.kubernetes.io/component: slack-bot
    app.kubernetes.io/part-of: bruno-infrastructure
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  # To encode: echo -n "your-token" | base64
  SLACK_BOT_TOKEN: ""  # Replace with actual base64 encoded token
  SLACK_SIGNING_SECRET: ""  # Replace with actual base64 encoded secret
  SLACK_APP_TOKEN: ""  # Replace with actual base64 encoded token
  LOGFIRE_TOKEN: ""  # Replace with actual base64 encoded Logfire token
