---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-ingress
spec:
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: gateway
      version: 1.25.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  install:
    createNamespace: false
  values:
    # Gateway configuration
    service:
      type: NodePort
      ports:
        - port: 80
          targetPort: 8080
          nodePort: 30080
          name: http2
        - port: 443
          targetPort: 8443
          nodePort: 30443
          name: https
      
      # LoadBalancer configuration
      loadBalancerIP: ""
      loadBalancerSourceRanges: []
    
    # Gateway labels
    labels:
      app: istio-ingressgateway
      istio: ingressgateway
    
    # Resource allocation (low CPU as per user preference)
    # resources:
    #   requests:
    #     cpu: 100m
    #     memory: 128Mi
    #   limits:
    #     cpu: 1000m
    #     memory: 1Gi
    
    # Security context
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      capabilities:
        drop:
          - ALL
    
    # Autoscaling configuration
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80
    
    # Pod disruption budget
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
    
    # Node selection for control-plane (Kind cluster uses ingress-ready label)
    nodeSelector:
      ingress-ready: "true"
    
    # Tolerations for control-plane scheduling
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
    
    # Affinity rules to prefer control-plane (Kind cluster uses ingress-ready label)
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: ingress-ready
              operator: In
              values: ["true"]
