---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: istiod
      version: 1.25.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  install:
    createNamespace: false
  values:
    # Ambient profile configuration
    profile: ambient
    
    # Pilot configuration
    pilot:
      # Resource allocation (low CPU as per user preference)
      # resources:
      #   requests:
      #     cpu: 100m
      #     memory: 128Mi
      #   limits:
      #     cpu: 1000m
      #     memory: 1Gi
      
      # Metrics configuration
      metrics:
        enabled: true
      
      # Security context
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
    
    # Global configuration
    global:
      # Disable sidecar injection for ambient mode
      sidecarInjectorWebhook:
        enabled: false
      
      # CNI configuration
      cni:
        enabled: true
      
      # Proxy configuration
      proxy:
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 128Mi
        #   limits:
        #     cpu: 2000m
        #     memory: 1Gi
    
    # Node selection for control-plane
    nodeSelector:
      node-role.kubernetes.io/control-plane: ""
    
    # Tolerations for control-plane scheduling
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
    
    # Affinity rules to prefer control-plane
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists