---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bruno-site
  namespace: bruno
spec:
  interval: 5m
  chart:
    spec:
      chart: ./chart
      version: 0.1.9
      sourceRef:
        kind: GitRepository
        name: bruno-site
        namespace: flux-system
  values:
    ingress:
      enabled: true
      className: ngrok
      hosts:
        - host: lucena.cloud
    monitoring:
      enabled: true
      prometheus:
        enabled: true
        servicemonitor:
          enabled: true
      grafana:
        enabled: true
        dashboard:
          enabled: true