---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bruno-site
  namespace: bruno
spec:
  interval: 5m
  chart:
    spec:
      chart: bruno-site
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: bruno-site-chart
        namespace: flux-system