---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bruno-site
  namespace: bruno
spec:
  interval: 5m
  chart:
    spec:
      chart: ./chart
      version: 0.1.0
      sourceRef:
        kind: GitRepository
        name: bruno-site
        namespace: flux-system
  values:
    ingress:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/hostname: lucena.cloud
      hosts:
        - host: lucena.cloud
          paths:
            - path: /
              pathType: Prefix
              service: frontend
      tls:
        - secretName: bruno-site-tls
          hosts:
            - lucena.cloud