---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bruno-site
  namespace: bruno
spec:
  interval: 5m
  chart:
    spec:
      chart: bruno-site
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: bruno-site-chart
        namespace: flux-system
  values:
    nodeSelector:
      role: tenant
      tenant: bruno
    ingress:
      enabled: true
      className: nginx
      # annotations:
      #   nginx.ingress.kubernetes.io/rewrite-target: /
      #   nginx.ingress.kubernetes.io/ssl-redirect: "true"
      #   cert-manager.io/cluster-issuer: "bruno-site"
      #   nginx.ingress.kubernetes.io/cors-allow-origin: "*"
      #   nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
      #   nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"
      # tls:
      #   enabled: true
      #   secretName: bruno-site-tls
      #   hosts:
      #     - lucena.cloud
      hosts:
        - host: lucena.cloud
          paths:
            - path: /
              pathType: Prefix
              serviceName: frontend-service
              servicePort: 80