---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bruno-site
  namespace: bruno
spec:
  interval: 5m
  chart:
    spec:
      chart: ./chart
      version: 0.1.0
      sourceRef:
        kind: GitRepository
        name: bruno-site
        namespace: flux-system
  values:
    ingress:
      enabled: true
      className: ngrok
      hosts:
        - host: lucena.cloud
          paths:
            - path: /
              pathType: Prefix
              service:
                name: bruno-site-frontend
                port:
                  number: 80
