---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bruno-site
  namespace: bruno-site
spec:
  interval: 5m
  chart:
    spec:
      chart: portfolio
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: bruno-site-chart
        namespace: bruno-site
  values:
    # Override only what's specific to studio environment
    global:
      environment: studio
    
    # Use production-ready replica counts
    api:
      replicaCount: 2
      autoscaling:
        minReplicas: 2
    
    frontend:
      replicaCount: 2
      autoscaling:
        minReplicas: 2