---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway-api
  labels:
    name: gateway-api
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: gateway-api-crds
  namespace: gateway-api
spec:
  interval: 1h0m0s
  url: oci://ghcr.io/kubernetes-sigs/gateway-api
  ref:
    tag: v1.3.0
  ignore: |
    /*
    !/standard-install.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-crds
  namespace: gateway-api
spec:
  interval: 1h0m0s
  sourceRef:
    kind: OCIRepository
    name: gateway-api-crds
  path: "./"
  prune: true
  wait: true
