---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: istio-system
spec:
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: cni
      version: 1.25.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  install:
    createNamespace: false
  values:
    # Ambient profile configuration
    profile: ambient
    
    # CNI configuration
    cni:
      # Resource allocation (low CPU as per user preference)
      # resources:
      #   requests:
      #     cpu: 100m
      #     memory: 128Mi
      #   limits:
      #     cpu: 1000m
      #     memory: 1Gi
      
      # Security context
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
      
      # Logging configuration
      logLevel: info
      
      # Exclude namespaces
      excludeNamespaces:
        - istio-system
        - kube-system
        - kube-public
        - kube-node-lease
