---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ztunnel
  namespace: istio-system
spec:
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: ztunnel
      version: 1.25.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  install:
    createNamespace: false
  values:
    # Ztunnel configuration
    ztunnel:
      # Resource allocation (low CPU as per user preference)
      # resources:
      #   requests:
      #     cpu: 100m
      #     memory: 128Mi
      #   limits:
      #     cpu: 1000m
      #     memory: 1Gi
      
      # Security context
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
      
      # Logging configuration
      logLevel: info
      
      # Metrics configuration
      metrics:
        enabled: true
        port: 15020
      
      # Node selection
      nodeSelector: {}
      
      # Tolerations for node scheduling
      tolerations: []
      
      # Affinity rules
      affinity: {}
