---
# Linkerd Trust Anchor Certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  secretName: linkerd-trust-anchor
  issuerRef:
    name: linkerd-trust-anchor
    kind: ClusterIssuer
  commonName: identity.linkerd.cluster.local
  duration: 24h
  renewBefore: 1h

---
# Linkerd Identity Issuer Certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
spec:
  secretName: linkerd-identity-issuer
  issuerRef:
    name: linkerd-trust-anchor
    kind: ClusterIssuer
  commonName: identity.linkerd.cluster.local
  duration: 24h
  renewBefore: 1h

---
# Linkerd Proxy Injector Certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-proxy-injector-k8s-tls
  namespace: linkerd
spec:
  secretName: linkerd-proxy-injector-k8s-tls
  issuerRef:
    name: linkerd-trust-anchor
    kind: ClusterIssuer
  commonName: linkerd-proxy-injector.linkerd.svc
  duration: 24h
  renewBefore: 1h

---
# Linkerd Policy Validator Certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-policy-validator-k8s-tls
  namespace: linkerd
spec:
  secretName: linkerd-policy-validator-k8s-tls
  issuerRef:
    name: linkerd-trust-anchor
    kind: ClusterIssuer
  commonName: linkerd-policy-validator.linkerd.svc
  duration: 24h
  renewBefore: 1h

---
# Linkerd SP Validator Certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-sp-validator-k8s-tls
  namespace: linkerd
spec:
  secretName: linkerd-sp-validator-k8s-tls
  issuerRef:
    name: linkerd-trust-anchor
    kind: ClusterIssuer
  commonName: linkerd-sp-validator.linkerd.svc
  duration: 24h
  renewBefore: 1h
