apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-crds
  namespace: linkerd
spec:
  interval: 5m
  chart:
    spec:
      chart: linkerd-crds
      version: "2025.9.1"
      sourceRef:
        kind: HelmRepository
        name: linkerd-edge
        namespace: flux-system
  values:
    installGatewayAPI: false
