---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster-studio
  namespace: rabbitmq-studio
  labels:
    app: rabbitmq
    environment: studio
    tier: messaging
    purpose: development
  annotations:
    rabbitmq.com/topology-allowed-namespaces: "knative-serving,knative-eventing,rabbitmq-studio"
spec:
  replicas: 1
  image: rabbitmq:3.12-management-alpine
  
  # Resource configuration (matching notifi local/dev setup)
  resources:
    requests:
      cpu: "100m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  
  # Persistence configuration
  persistence:
    storageClassName: "standard"
    storage: 1Gi
  
  # Tolerations for node scheduling (matching notifi setup)
  tolerations:
    - key: "knative"
      operator: Equal
      value: "true"
      effect: NoSchedule
  
  # RabbitMQ configuration
  rabbitmq:
    additionalPlugins:
      - rabbitmq_management
    additionalConfig: |
      # Absolute memory limit for containers (per RabbitMQ docs)
      vm_memory_high_watermark.absolute = 256MiB
      total_memory_available_override_value = 536870912
      
      # Container-optimized settings with reduced disk requirements
      disk_free_limit.absolute = 200MB
      heartbeat = 60
      collect_statistics = none
      
      # Erlang VM optimizations for containers
      vm_memory_calculation_strategy = allocated
      
      # Studio-specific settings
      log.console.level = info
