---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kamaji
  namespace: kamaji-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kamaji
      version: 0.0.0+latest
      sourceRef:
        kind: HelmRepository
        name: clastix
        namespace: flux-system
  values:
    resources: null
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: clastix
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://clastix.github.io/charts 