apiVersion: apps/v1
kind: Deployment
metadata:
  name: statuspage-exporter
  namespace: statuspage-exporter
  labels:
    app.kubernetes.io/name: statuspage-exporter
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: statuspage-exporter
      app.kubernetes.io/component: monitoring
  template:
    metadata:
      labels:
        app.kubernetes.io/name: statuspage-exporter
        app.kubernetes.io/component: monitoring
        app.kubernetes.io/part-of: homelab
    spec:
      containers:
      - name: statuspage-exporter
        image: ghcr.io/sergeyshevch/statuspage-exporter:latest
        imagePullPolicy: Always
        args:
          - --statuspages=https://status.aws.amazon.com,https://status.cursor.sh
          - --listen-address=:9747
        ports:
        - name: metrics
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
      restartPolicy: Always
