apiVersion: v1
kind: Namespace
metadata:
  name: statuspage-exporter
  labels:
    name: statuspage-exporter
    app.kubernetes.io/name: statuspage-exporter
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: homelab
