apiVersion: v1
kind: Service
metadata:
  name: statuspage-exporter
  namespace: statuspage-exporter
  labels:
    app.kubernetes.io/name: statuspage-exporter
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: homelab
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9747
    targetPort: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/name: statuspage-exporter
    app.kubernetes.io/component: monitoring
