apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: studio
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux/clusters/studio
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system 