apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falcosidekick
  namespace: falcosidekick
spec:
  interval: 5m
  chart:
    spec:
      chart: falcosidekick
      version: 0.4.0
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: flux-system
  values:
    falcosidekick:
      # Enable Falcosidekick
      enabled: true
      
      # Configuration
      config:
        # AlertManager integration
        alertmanager:
          enabled: true
          hostport: "alertmanager-operated.prometheus:9093"
          path: "/api/v1/alerts"
          customHeaders:
            Content-Type: "application/json"
        
        # Slack integration (optional - uncomment and configure as needed)
        # slack:
        #   enabled: false
        #   webhookurl: ""
        #   channel: ""
        #   iconemoji: ":warning:"
        #   username: "Falco Security"
        
        # Discord integration (optional - uncomment and configure as needed)
        # discord:
        #   enabled: false
        #   webhookurl: ""
        #   icon: ""
        #   username: "Falco Security"
        
        # Webhook integration for custom endpoints
        webhook:
          enabled: false
          address: ""
          customHeaders: {}
        
        # Elasticsearch integration (optional)
        # elasticsearch:
        #   enabled: false
        #   hostport: ""
        #   index: "falco"
        #   type: "event"
        #   username: ""
        #   password: ""
        
        # Influxdb integration (optional)
        # influxdb:
        #   enabled: false
        #   hostport: ""
        #   database: "falco"
        #   precision: "ns"
        #   measurement: "falco_events"
        #   username: ""
        #   password: ""
        
        # Loki integration (optional - for log aggregation)
        # loki:
        #   enabled: false
        #   hostport: ""
        #   username: ""
        #   password: ""
        #   tenant: ""
        #   labels: ""

      # Resource limits
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi

      # Security context
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        readOnlyRootFilesystem: true

      # Node selector for observability nodes
      nodeSelector:
        role: observability

      # Tolerations for observability nodes
      tolerations:
        - key: "role"
          operator: "Equal"
          value: "observability"
          effect: "NoSchedule"

      # Service account configuration
      serviceAccount:
        create: true
        annotations: {}
        name: "falcosidekick"

      # Service configuration
      service:
        type: ClusterIP
        port: 2801
        targetPort: 2801

      # Ingress configuration (optional - for external access)
      ingress:
        enabled: false
        className: nginx
        hosts:
          - host: falcosidekick.lucena.cloud
            paths:
              - path: /
                pathType: Prefix
        tls: []
