apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: external-dns
  namespace: external-dns

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: external-dns
  app.kubernetes.io/part-of: infrastructure
