apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: notifi-mocks

namespace: notifi-mocks

resources:
  - namespace.yaml
  - infrastructure.yaml
  - linkerd-policies.yaml 
  # - tests/tests.yaml