# Generic Linkerd Server Configuration for Notifi Services
# This file provides comprehensive Server and ServerAuthorization resources
# for all Notifi service types in the mocks namespace.
#
# Service Types Covered:
# - Test Infrastructure (port 8080)
# - Gateway Services (port 80)
# - gRPC Services (port 4000)
# - Messenger Services (port 5000)
# - Proxy Services (port 7000)
# - Database Services (port 8123)
# - Cache Services (port 6379)
# - Monitoring Services (port 5000)
# - Scheduler Services (port 4000)
# - Processor Services (port 5000)
# - Broker Services (port 4000)
# - Handler Services (port 5000)
# - Service Components (port 5000)
# - Storage Services (port 9000)
# - Analytics Services (port 8080)
# - Worker Services (port 8080)
# - API Services (port 80, 443)
# - WebSocket Services (port 8080)
# - Queue Services (port 5672)
# - Search Services (port 9200)

---
# Default Server for Test Infrastructure Services
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: test-infrastructure-server
  namespace: mocks
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: test-infrastructure
  port: 8080
  proxyProtocol: HTTP/1

---
# Server Authorization for Test Infrastructure Services
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: test-infrastructure-auth
  namespace: mocks
spec:
  server:
    name: test-infrastructure-server
  client:
    networks:
    - cidr: 10.0.0.0/8
    - cidr: 172.16.0.0/12
    - cidr: 192.168.0.0/16
    meshTLS:
      identities:
      - "*.notifi.svc.cluster.local"
      - "*.prometheus.svc.cluster.local"
      - "*.loki.svc.cluster.local"

---
# Server for Gateway Services
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: gateway-server
  namespace: mocks
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: gateway
  port: 80
  proxyProtocol: HTTP/1

---
# Server Authorization for Gateway Services
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: gateway-auth
  namespace: mocks
spec:
  server:
    name: gateway-server
  client:
    networks:
    - cidr: 10.0.0.0/8
    - cidr: 172.16.0.0/12
    - cidr: 192.168.0.0/16
    meshTLS:
      identities:
      - "*.notifi.svc.cluster.local"

---
# Server for gRPC Services
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: grpc-server
  namespace: mocks
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: manager
  port: 4000
  proxyProtocol: HTTP/2

---
# Server Authorization for gRPC Services
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: grpc-auth
  namespace: mocks
spec:
  server:
    name: grpc-server
  client:
    networks:
    - cidr: 10.0.0.0/8
    - cidr: 172.16.0.0/12
    - cidr: 192.168.0.0/16
    meshTLS:
      identities:
      - "*.notifi.svc.cluster.local"

---
# Server for Messenger Services
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: messenger-server
  namespace: mocks
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: messenger
  port: 5000
  proxyProtocol: HTTP/1

---
# Server Authorization for Messenger Services
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: messenger-auth
  namespace: mocks
spec:
  server:
    name: messenger-server
  client:
    networks:
    - cidr: 10.0.0.0/8
    - cidr: 172.16.0.0/12
    - cidr: 192.168.0.0/16
    meshTLS:
      identities:
      - "*.notifi.svc.cluster.local"

---
# Server for Proxy Services
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: proxy-server
  namespace: mocks
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: proxy
  port: 7000
  proxyProtocol: HTTP/1

---
# Server Authorization for Proxy Services
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: proxy-auth
  namespace: mocks
spec:
  server:
    name: proxy-server
  client:
    networks:
    - cidr: 10.0.0.0/8
    - cidr: 172.16.0.0/12
    - cidr: 192.168.0.0/16
    meshTLS:
      identities:
      - "*.notifi.svc.cluster.local"

---
# Server for Database Services
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: database-server
  namespace: mocks
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: database
  port: 8123
  proxyProtocol: HTTP/1

---
# Server Authorization for Database Services
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: database-auth
  namespace: mocks
spec:
  server:
    name: database-server
  client:
    networks:
    - cidr: 10.0.0.0/8
    - cidr: 172.16.0.0/12
    - cidr: 192.168.0.0/16
    meshTLS:
      identities:
      - "*.notifi.svc.cluster.local"

---
# Server for Cache Services
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: cache-server
  namespace: mocks
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: cache
  port: 6379
  proxyProtocol: opaque

---
# Server Authorization for Cache Services
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: cache-auth
  namespace: mocks
spec:
  server:
    name: cache-server
  client:
    networks:
    - cidr: 10.0.0.0/8
    - cidr: 172.16.0.0/12
    - cidr: 192.168.0.0/16
    meshTLS:
      identities:
      - "*.notifi.svc.cluster.local"

---
# Server for Monitoring Services
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: monitoring-server
  namespace: mocks
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: monitoring
  port: 5000
  proxyProtocol: HTTP/1

---
# Server Authorization for Monitoring Services
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: monitoring-auth
  namespace: mocks
spec:
  server:
    name: monitoring-server
  client:
    networks:
    - cidr: 10.0.0.0/8
    - cidr: 172.16.0.0/12
    - cidr: 192.168.0.0/16
    meshTLS:
      identities:
      - "*.notifi.svc.cluster.local"
      - "*.prometheus.svc.cluster.local"
      - "*.loki.svc.cluster.local"

---
# Server for Scheduler Services
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: scheduler-server
  namespace: mocks
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: scheduler
  port: 4000
  proxyProtocol: HTTP/2

---
# Server Authorization for Scheduler Services
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: scheduler-auth
  namespace: mocks
spec:
  server:
    name: scheduler-server
  client:
    networks:
    - cidr: 10.0.0.0/8
    - cidr: 172.16.0.0/12
    - cidr: 192.168.0.0/16
    meshTLS:
      identities:
      - "*.notifi.svc.cluster.local"

---
# Server for Processor Services
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: processor-server
  namespace: mocks
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: processor
  port: 5000
  proxyProtocol: HTTP/1

---
# Server Authorization for Processor Services
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: processor-auth
  namespace: mocks
spec:
  server:
    name: processor-server
  client:
    networks:
    - cidr: 10.0.0.0/8
    - cidr: 172.16.0.0/12
    - cidr: 192.168.0.0/16
    meshTLS:
      identities:
      - "*.notifi.svc.cluster.local"

---
# Server for Broker Services
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: broker-server
  namespace: mocks
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: broker
  port: 4000
  proxyProtocol: HTTP/2

---
# Server Authorization for Broker Services
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: broker-auth
  namespace: mocks
spec:
  server:
    name: broker-server
  client:
    networks:
    - cidr: 10.0.0.0/8
    - cidr: 172.16.0.0/12
    - cidr: 192.168.0.0/16
    meshTLS:
      identities:
      - "*.notifi.svc.cluster.local"

---
# Server for Handler Services
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: handler-server
  namespace: mocks
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: handler
  port: 5000
  proxyProtocol: HTTP/1

---
# Server Authorization for Handler Services
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: handler-auth
  namespace: mocks
spec:
  server:
    name: handler-server
  client:
    networks:
    - cidr: 10.0.0.0/8
    - cidr: 172.16.0.0/12
    - cidr: 192.168.0.0/16
    meshTLS:
      identities:
      - "*.notifi.svc.cluster.local"

---
# Server for Service Components
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: service-server
  namespace: mocks
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: service
  port: 5000
  proxyProtocol: HTTP/1

---
# Server Authorization for Service Components
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: service-auth
  namespace: mocks
spec:
  server:
    name: service-server
  client:
    networks:
    - cidr: 10.0.0.0/8
    - cidr: 172.16.0.0/12
    - cidr: 192.168.0.0/16
    meshTLS:
      identities:
      - "*.notifi.svc.cluster.local"
      - "*.prometheus.svc.cluster.local"
      - "*.loki.svc.cluster.local"
      - "*.grafana.svc.cluster.local"

---
# Server for Storage Services
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: storage-server
  namespace: mocks
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: storage
  port: 9000
  proxyProtocol: HTTP/1

---
# Server Authorization for Storage Services
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: storage-auth
  namespace: mocks
spec:
  server:
    name: storage-server
  client:
    networks:
    - cidr: 10.0.0.0/8
    - cidr: 172.16.0.0/12
    - cidr: 192.168.0.0/16
    meshTLS:
      identities:
      - "*.notifi.svc.cluster.local"
      - "*.prometheus.svc.cluster.local"
      - "*.loki.svc.cluster.local"
      - "*.grafana.svc.cluster.local"

---
# Server for Analytics Services
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: analytics-server
  namespace: mocks
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: analytics
  port: 8080
  proxyProtocol: HTTP/1

---
# Server Authorization for Analytics Services
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: analytics-auth
  namespace: mocks
spec:
  server:
    name: analytics-server
  client:
    networks:
    - cidr: 10.0.0.0/8
    - cidr: 172.16.0.0/12
    - cidr: 192.168.0.0/16
    meshTLS:
      identities:
      - "*.notifi.svc.cluster.local"
      - "*.prometheus.svc.cluster.local"
      - "*.loki.svc.cluster.local"
      - "*.grafana.svc.cluster.local"

---
# Server for Worker Services
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: worker-server
  namespace: mocks
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: worker
  port: 8080
  proxyProtocol: HTTP/1

---
# Server Authorization for Worker Services
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: worker-auth
  namespace: mocks
spec:
  server:
    name: worker-server
  client:
    networks:
    - cidr: 10.0.0.0/8
    - cidr: 172.16.0.0/12
    - cidr: 192.168.0.0/16
    meshTLS:
      identities:
      - "*.notifi.svc.cluster.local"
      - "*.prometheus.svc.cluster.local"
      - "*.loki.svc.cluster.local"
      - "*.grafana.svc.cluster.local"

---
# Server for API Services
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: api-server
  namespace: mocks
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: api
  port: 80
  proxyProtocol: HTTP/1

---
# Server Authorization for API Services
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: api-auth
  namespace: mocks
spec:
  server:
    name: api-server
  client:
    networks:
    - cidr: 10.0.0.0/8
    - cidr: 172.16.0.0/12
    - cidr: 192.168.0.0/16
    meshTLS:
      identities:
      - "*.notifi.svc.cluster.local"
      - "*.prometheus.svc.cluster.local"
      - "*.loki.svc.cluster.local"
      - "*.grafana.svc.cluster.local"

---
# Server for WebSocket Services
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: websocket-server
  namespace: mocks
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: websocket
  port: 8080
  proxyProtocol: HTTP/1

---
# Server Authorization for WebSocket Services
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: websocket-auth
  namespace: mocks
spec:
  server:
    name: websocket-server
  client:
    networks:
    - cidr: 10.0.0.0/8
    - cidr: 172.16.0.0/12
    - cidr: 192.168.0.0/16
    meshTLS:
      identities:
      - "*.notifi.svc.cluster.local"
      - "*.prometheus.svc.cluster.local"
      - "*.loki.svc.cluster.local"
      - "*.grafana.svc.cluster.local"

---
# Server for Queue Services
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: queue-server
  namespace: mocks
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: queue
  port: 5672
  proxyProtocol: opaque

---
# Server Authorization for Queue Services
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: queue-auth
  namespace: mocks
spec:
  server:
    name: queue-server
  client:
    networks:
    - cidr: 10.0.0.0/8
    - cidr: 172.16.0.0/12
    - cidr: 192.168.0.0/16
    meshTLS:
      identities:
      - "*.notifi.svc.cluster.local"
      - "*.prometheus.svc.cluster.local"
      - "*.loki.svc.cluster.local"
      - "*.grafana.svc.cluster.local"

---
# Server for Search Services
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: search-server
  namespace: mocks
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: search
  port: 9200
  proxyProtocol: HTTP/1

---
# Server Authorization for Search Services
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: search-auth
  namespace: mocks
spec:
  server:
    name: search-server
  client:
    networks:
    - cidr: 10.0.0.0/8
    - cidr: 172.16.0.0/12
    - cidr: 192.168.0.0/16
    meshTLS:
      identities:
      - "*.notifi.svc.cluster.local"
      - "*.prometheus.svc.cluster.local"
      - "*.loki.svc.cluster.local"
      - "*.grafana.svc.cluster.local"




