apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k6-operator
  namespace: k6-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: k6-operator
      version: "3.16.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    installCRDs: true
