---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: lucena-cloud-canary-alerts
  namespace: cloudflare-tunnel
  labels:
    app: kube-prometheus-stack
    release: prometheus-operator
    component: canary-monitoring
spec:
  groups:
  - name: lucena-cloud-canary.rules
    rules:
    # External Canary - HTTP Availability
    - alert: LucenaCloudHTTPDown
      expr: probe_success{job="lucena-cloud-http", probe="http_2xx"} == 0
      for: 2m
      labels:
        severity: critical
        category: availability
        component: canary-monitoring
        domain: lucena.cloud
      annotations:
        summary: "lucena.cloud HTTP endpoint is down"
        description: "External canary check for lucena.cloud HTTP endpoint is failing. The site may be inaccessible from the internet."
        runbook_url: "https://github.com/brunolucena/home/blob/main/flux/clusters/studio/infrastructure/cloudflare-tunnel/README.md#troubleshooting"
        dashboard_url: "https://grafana.home.local/d/lucena-cloud"

    # External Canary - HTTPS Availability
    - alert: LucenaCloudHTTPSDown
      expr: probe_success{job="lucena-cloud-https", probe="http_2xx"} == 0
      for: 2m
      labels:
        severity: critical
        category: availability
        component: canary-monitoring
        domain: lucena.cloud
      annotations:
        summary: "lucena.cloud HTTPS endpoint is down"
        description: "External canary check for lucena.cloud HTTPS endpoint is failing. The site may be inaccessible from the internet."
        runbook_url: "https://github.com/brunovlucena/home/blob/main/flux/clusters/studio/infrastructure/cloudflare-tunnel/README.md#troubleshooting"

    # External Canary - Response Time High
    - alert: LucenaCloudHighResponseTime
      expr: probe_duration_seconds{job=~"lucena-cloud-.*"} > 5
      for: 5m
      labels:
        severity: warning
        category: performance
        component: canary-monitoring
        domain: lucena.cloud
      annotations:
        summary: "lucena.cloud response time is high"
        description: "External canary check for lucena.cloud shows response time of {{ $value }}s, which is above the 5s threshold."
        runbook_url: "https://github.com/brunovlucena/home/blob/main/flux/clusters/studio/infrastructure/cloudflare-tunnel/README.md#troubleshooting"

    # External Canary - SSL Certificate Expiring
    - alert: LucenaCloudSSLCertExpiring
      expr: (probe_ssl_earliest_cert_expiry{job="lucena-cloud-https"} - time()) / 86400 < 30
      for: 0m
      labels:
        severity: warning
        category: security
        component: canary-monitoring
        domain: lucena.cloud
      annotations:
        summary: "lucena.cloud SSL certificate expiring soon"
        description: "SSL certificate for lucena.cloud expires in {{ $value }} days."
        runbook_url: "https://github.com/brunovlucena/home/blob/main/flux/clusters/studio/infrastructure/cloudflare-tunnel/README.md#troubleshooting"

    # External Canary - DNS Resolution Issues
    - alert: LucenaCloudDNSResolutionFailed
      expr: probe_dns_lookup_time_seconds{job="lucena-cloud-dns"} == 0 and probe_success{job="lucena-cloud-dns"} == 0
      for: 1m
      labels:
        severity: critical
        category: dns
        component: canary-monitoring
        domain: lucena.cloud
      annotations:
        summary: "lucena.cloud DNS resolution failed"
        description: "External canary cannot resolve lucena.cloud DNS. This may indicate DNS or tunnel connectivity issues."
        runbook_url: "https://github.com/brunovlucena/home/blob/main/flux/clusters/studio/infrastructure/cloudflare-tunnel/README.md#troubleshooting"

    # External Canary - Multiple Endpoints Down
    - alert: LucenaCloudMultipleEndpointsDown
      expr: (count(probe_success{job=~"lucena-cloud-.*"} == 1) < 2)
      for: 1m
      labels:
        severity: critical
        category: availability
        component: canary-monitoring
        domain: lucena.cloud
      annotations:
        summary: "Multiple lucena.cloud endpoints are down"
        description: "{{ $value }} lucena.cloud endpoints are down. The site may be completely inaccessible."
        runbook_url: "https://github.com/brunovlucena/home/blob/main/flux/clusters/studio/infrastructure/cloudflare-tunnel/README.md#troubleshooting"

    # External Canary - Connectivity vs Tunnel Health Correlation
    - alert: LucenaCloudTunnelCorrelationAlert
      expr: (probe_success{job=~"lucena-cloud-.*"} == 0) and (up{job="cloudflare-tunnel", namespace="cloudflare-tunnel"} == 0)
      for: 1m
      labels:
        severity: critical
        category: correlation
        component: canary-monitoring
        domain: lucena.cloud
      annotations:
        summary: "lucena.cloud down and Cloudflare tunnel is down"
        description: "External canary shows lucena.cloud is down AND Cloudflare tunnel is down. This indicates a tunnel connectivity issue rather than internet connectivity."
        runbook_url: "https://github.com/brunovlucena/home/blob/main/flux/clusters/studio/infrastructure/cloudflare-tunnel/README.md#troubleshooting"

---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: lucena-cloud-http
  namespace: cloudflare-tunnel
  labels:
    app: kube-prometheus-stack
    release: prometheus-operator
    component: canary-monitoring
spec:
  jobName: lucena-cloud-http
  prober:
    http:
      preferredScheme: http
  targets:
    staticConfig:
      static:
      - lucena.cloud
  module: http_2xx
  interval: 30s

---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: lucena-cloud-https
  namespace: cloudflare-tunnel
  labels:
    app: kube-prometheus-stack
    release: prometheus-operator
    component: canary-monitoring
spec:
  jobName: lucena-cloud-https
  prober:
    http:
      preferredScheme: https
  targets:
    staticConfig:
      static:
      - lucena.cloud
  module: http_2xx
  interval: 30s

---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: lucena-cloud-dns
  namespace: cloudflare-tunnel
  labels:
    app: kube-prometheus-stack
    release: prometheus-operator
    component: canary-monitoring
spec:
  jobName: lucena-cloud-dns
  prober:
    dns:
      queryName: lucena.cloud
      queryType: A
      validRcodes:
      - NOERROR
  targets:
    staticConfig:
      static:
      - 1.1.1.1:53
  interval: 30s
