# 🌐 Example Service for Testing Cloudflare Tunnel
# 
# This is an example httpbin service that can be used to test
# the Cloudflare tunnel connectivity. It's based on the official
# Cloudflare Kubernetes deployment guide.
#
# To use this service:
# 1. Apply this manifest: kubectl apply -f example-service.yaml
# 2. Configure a tunnel route in Cloudflare Zero Trust dashboard
# 3. Point the route to: http://httpbin-service.cloudflare-tunnel.svc.cluster.local

apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-deployment
  namespace: cloudflare-tunnel
  labels:
    app.kubernetes.io/name: httpbin
    app.kubernetes.io/component: test-service
    app.kubernetes.io/part-of: home-infrastructure
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
        app.kubernetes.io/name: httpbin
        app.kubernetes.io/component: test-service
        app.kubernetes.io/part-of: home-infrastructure
    spec:
      containers:
        - name: httpbin
          image: kennethreitz/httpbin:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /status/200
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /status/200
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin-service
  namespace: cloudflare-tunnel
  labels:
    app.kubernetes.io/name: httpbin
    app.kubernetes.io/component: test-service
    app.kubernetes.io/part-of: home-infrastructure
spec:
  type: ClusterIP
  selector:
    app: httpbin
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
