apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cloudflare-tunnel
  namespace: flux-system

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - tunnel-token-sealed-secret.yaml
  # Uncomment the line below to include the example service for testing
  # - example-service.yaml
