apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cloudflare-tunnel
  namespace: flux-system

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  # Uncomment the line below to include the example service for testing
  # - example-service.yaml

# Note: The tunnel-token secret is not included in this kustomization
# because it contains sensitive data. Use the create-tunnel-secret.sh script
# to create the secret manually, or manage it through your secret management system.
