apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cloudflare-tunnel
  namespace: flux-system

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  # Uncomment the line below to include the example service for testing
  # - example-service.yaml
  # Uncomment the line below to include the sealed secret (after running create-tunnel-sealed-secret.sh)
  # - tunnel-token-sealed-secret.yaml

# Note: The tunnel-token sealed secret is not included by default.
# Run ./create-tunnel-sealed-secret.sh <tunnel_token> to create it,
# then uncomment the line above to include it in the kustomization.
