apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-prometheus-operator-kube-p-alertmanager
  namespace: prometheus
  labels:
    app: kube-prometheus-stack-alertmanager
spec:
  route:
    groupBy: ['alertname']
    groupWait: 10s
    groupInterval: 10s
    repeatInterval: 1h
    receiver: 'slack-default'
    routes:
    - matchers:
      - name: severity
        value: critical
      receiver: 'pagerduty-critical'
    - matchers:
      - name: severity
        value: warning
      receiver: 'slack-warning'
    - matchers:
      - name: severity
        value: info
      receiver: 'slack-info'
  receivers:
  - name: 'pagerduty-critical'
    pagerdutyConfigs:
    - serviceKey:
        name: pagerduty-secrets
        key: pagerduty-service-key
      description: '{{ .GroupLabels.alertname }}'
      details:
      - key: summary
        value: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
      - key: severity
        value: '{{ .GroupLabels.severity }}'
      - key: namespace
        value: '{{ .GroupLabels.namespace }}'
      - key: instance
        value: '{{ .GroupLabels.instance }}'
      client: 'Alertmanager'
      clientURL: '{{ .ExternalURL }}'
      severity: 'critical'
      component: '{{ .GroupLabels.alertname }}'
      group: '{{ .GroupLabels.alertname }}'
      class: '{{ .GroupLabels.alertname }}'
  - name: 'slack-default'
    slackConfigs:
    - apiURL:
        name: pagerduty-secrets
        key: slack-webhook-url
      channel: '#jamie-sre-chatbot'
      title: 'Alert: {{ .GroupLabels.alertname }}'
      text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
      sendResolved: true
  - name: 'slack-warning'
    slackConfigs:
    - apiURL:
        name: pagerduty-secrets
        key: slack-webhook-url
      channel: '#jamie-sre-chatbot'
      title: '⚠️ Warning: {{ .GroupLabels.alertname }}'
      text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
      sendResolved: true
  - name: 'slack-critical'
    slackConfigs:
    - apiURL:
        name: pagerduty-secrets
        key: slack-webhook-url
      channel: '#jamie-sre-chatbot'
      title: 'ℹ️ Critical: {{ .GroupLabels.alertname }}'
      text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
      sendResolved: true
  inhibitRules:
  - targetMatch:
    - name: severity
      value: warning
      matchType: =~
    - name: severity
      value: info
      matchType: =~
    sourceMatch:
    - name: severity
      value: critical
      matchType: =
    equal:
    - namespace
    - alertname
  - targetMatch:
    - name: severity
      value: info
      matchType: =
    sourceMatch:
    - name: severity
      value: warning
      matchType: =
    equal:
    - namespace
    - alertname
