# Grafana Notification Policies Configuration
# This file defines notification routing policies for Grafana alerting

apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-notification-policies
  namespace: prometheus
  labels:
    app: kube-prometheus-stack-grafana
    grafana_notification_policies: "true"
    grafana_datasource: "1"
data:
  notification-policies.yaml: |
    # Grafana Notification Policies
    # Routes alerts based on severity and labels
    
    # Root Policy - Default routing
    receiver: slack-info
    groupBy: ['alertname', 'severity', 'namespace']
    groupWait: 10s
    groupInterval: 10s
    repeatInterval: 1h
    
    # Policy Tree
    policies:
      # Critical Alerts - Route to PagerDuty
      - receiver: pagerduty-critical
        groupBy: ['alertname', 'severity']
        groupWait: 0s
        groupInterval: 5s
        repeatInterval: 30m
        matchers:
          - label: severity
            match: "critical"
            matchType: "="
      
      # Warning Alerts - Route to Slack Warning
      - receiver: slack-warning
        groupBy: ['alertname', 'severity']
        groupWait: 10s
        groupInterval: 10s
        repeatInterval: 1h
        matchers:
          - label: severity
            match: "warning"
            matchType: "="
      
      # Info Alerts - Route to Slack Info
      - receiver: slack-info
        groupBy: ['alertname', 'severity']
        groupWait: 30s
        groupInterval: 30s
        repeatInterval: 2h
        matchers:
          - label: severity
            match: "info"
            matchType: "="
      
      # Security Alerts - Route to PagerDuty with high priority
      - receiver: pagerduty-critical
        groupBy: ['alertname', 'category']
        groupWait: 0s
        groupInterval: 5s
        repeatInterval: 15m
        matchers:
          - label: category
            match: "security"
            matchType: "="
      
      # Falco Alerts - Route to PagerDuty
      - receiver: pagerduty-critical
        groupBy: ['alertname', 'source']
        groupWait: 0s
        groupInterval: 5s
        repeatInterval: 15m
        matchers:
          - label: source
            match: "falco"
            matchType: "="
      
      # All Critical Alerts - Route to PagerDuty All
      - receiver: pagerduty-all
        groupBy: ['alertname', 'severity']
        groupWait: 0s
        groupInterval: 5s
        repeatInterval: 30m
        matchers:
          - label: severity
            match: "critical"
            matchType: "="
      
      # High Priority Warning Alerts - Route to PagerDuty All
      - receiver: pagerduty-all
        groupBy: ['alertname', 'priority']
        groupWait: 10s
        groupInterval: 10s
        repeatInterval: 1h
        matchers:
          - label: priority
            match: "high"
            matchType: "="
          - label: severity
            match: "warning"
            matchType: "="
      
      # Kubernetes Alerts - Route based on severity
      - receiver: slack-warning
        groupBy: ['alertname', 'namespace']
        groupWait: 10s
        groupInterval: 10s
        repeatInterval: 1h
        matchers:
          - label: namespace
            match: "kube-system|prometheus|grafana|alertmanager"
            matchType: "=~"
          - label: severity
            match: "warning"
            matchType: "="
      
      # Application Alerts - Route to Slack Info
      - receiver: slack-info
        groupBy: ['alertname', 'app']
        groupWait: 30s
        groupInterval: 30s
        repeatInterval: 2h
        matchers:
          - label: app
            match: ".*"
            matchType: "=~"
          - label: severity
            match: "info"
            matchType: "="
    
    # Mute Timings
    muteTimeIntervals:
      - name: maintenance-window
        timeIntervals:
          - times:
              - start_time: "02:00"
                end_time: "04:00"
            weekdays: ['sunday']
            months: ['1:12']
            years: ['2024:2030']
      
      - name: business-hours
        timeIntervals:
          - times:
              - start_time: "09:00"
                end_time: "17:00"
            weekdays: ['monday:friday']
    
    # Inhibition Rules
    inhibitRules:
      # Inhibit warning and info alerts when critical alerts are firing
      - targetMatchers:
          - label: severity
            match: "warning|info"
            matchType: "=~"
        sourceMatchers:
          - label: severity
            match: "critical"
            matchType: "="
        equal: ['alertname', 'namespace', 'instance']
      
      # Inhibit info alerts when warning alerts are firing
      - targetMatchers:
          - label: severity
            match: "info"
            matchType: "="
        sourceMatchers:
          - label: severity
            match: "warning"
            matchType: "="
        equal: ['alertname', 'namespace', 'instance']
