---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: prometheus
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 55.5.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    prometheus:
      prometheusSpec:
        nodeSelector:
          role: observability
        retention: 30d
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: standard
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 50Gi
        resources:
          requests:
            cpu: 250m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 4Gi
    grafana:
      adminPassword: admin # TODO: Sealed Secrets
      persistence:
        enabled: true
        storageClassName: standard
        size: 10Gi
      service:
        type: ClusterIP
      ingress:
        enabled: false
        ingressClassName: ngrok
        className: ngrok
        namespace: ngrok-operator
        hosts:
          - grafana.lucena.cloud
        path: /
        pathType: Prefix
    alertmanager:
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: standard
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi

