---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-mcp-server
  namespace: prometheus
  labels:
    app: prometheus-mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-mcp-server
  template:
    metadata:
      labels:
        app: prometheus-mcp-server
    spec:
      containers:
      - name: prometheus-mcp-server
        image: ghcr.io/pab1it0/prometheus-mcp-server:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PROMETHEUS_URL
          value: "http://prometheus-operator-kube-p-prometheus.prometheus.svc.cluster.local:9090"
        - name: PROMETHEUS_MCP_SERVER_TRANSPORT
          value: "sse"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-mcp-server
  namespace: prometheus
  labels:
    app: prometheus-mcp-server
spec:
  selector:
    app: prometheus-mcp-server
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
