---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-critical-alert
  namespace: prometheus
  labels:
    app: kube-prometheus-stack-alertmanager
    release: prometheus-operator
spec:
  groups:
  - name: test-alerts
    rules:
    - alert: TestCriticalAlert
      expr: vector(1)  # This will always evaluate to 1, triggering the alert
      for: 0s  # Fire immediately
      labels:
        severity: critical
        alertname: TestCriticalAlert
      annotations:
        summary: "Test Critical Alert - PagerDuty Integration Test"
        description: "This is a test alert to verify PagerDuty integration is working correctly. This alert will fire for 1 minute and then be automatically cleaned up."
        runbook_url: "https://github.com/brunovlucena/home/blob/main/flux/clusters/studio/infrastructure/prometheus-operator/test-critical-alert.yaml"
