apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k6-operator
  namespace: k6-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: k6-operator
      version: "3.14.2"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    manager:
      replicas: 1
      image:
        registry: ghcr.io
        repository: grafana/k6-operator
        tag: controller-v0.0.22
        pullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 250m
          memory: 256Mi
    rbac:
      create: true
    installCRDs: true
    namespace:
      create: false
