apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-golden-signals-chatbot
  namespace: k6-operator
  labels:
    app.kubernetes.io/name: k6-golden-signals-chatbot
    app.kubernetes.io/component: load-test
    app.kubernetes.io/part-of: bruno-infrastructure
spec:
  script:
    configMap:
      name: k6-golden-signals-chatbot
      file: golden-signals-chatbot.js
  arguments: --tag test_type=golden-signals --tag service=jamie-sre-chatbot
  parallelism: 1
