apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-golden-signals-test
  namespace: k6-operator
  labels:
    app.kubernetes.io/name: k6-golden-signals-test
    app.kubernetes.io/component: load-test
    app.kubernetes.io/part-of: bruno-infrastructure
spec:
  script:
    configMap:
      name: k6-golden-signals-test
      file: golden-signals-test.js
  arguments: --tag test_type=golden-signals --tag service=bruno-site
  parallelism: 1
