apiVersion: v1
kind: ServiceAccount
metadata:
  name: cursor
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: cursor-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: cursor
type: kubernetes.io/service-account-token
