apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cursor-readonly
rules:
# Allow read access to most resources
- apiGroups: [""]
  resources: 
    - pods
    - pods/log
    - pods/status
    - services
    - endpoints
    - persistentvolumeclaims
    - persistentvolumes
    - nodes
    - namespaces
    - configmaps
    - secrets
    - events
    - serviceaccounts
    - replicationcontrollers
  verbs: ["get", "list", "watch"]

# Allow read access to apps resources
- apiGroups: ["apps"]
  resources:
    - deployments
    - replicasets
    - statefulsets
    - daemonsets
  verbs: ["get", "list", "watch"]

# Allow read access to extensions resources
- apiGroups: ["extensions"]
  resources:
    - deployments
    - replicasets
    - ingresses
  verbs: ["get", "list", "watch"]

# Allow read access to networking resources
- apiGroups: ["networking.k8s.io"]
  resources:
    - ingresses
    - networkpolicies
  verbs: ["get", "list", "watch"]

# Allow read access to batch resources
- apiGroups: ["batch"]
  resources:
    - jobs
    - cronjobs
  verbs: ["get", "list", "watch"]

# Allow read access to autoscaling resources
- apiGroups: ["autoscaling"]
  resources:
    - horizontalpodautoscalers
  verbs: ["get", "list", "watch"]

# Allow read access to storage resources
- apiGroups: ["storage.k8s.io"]
  resources:
    - storageclasses
    - volumeattachments
  verbs: ["get", "list", "watch"]

# Allow read access to RBAC resources
- apiGroups: ["rbac.authorization.k8s.io"]
  resources:
    - roles
    - rolebindings
    - clusterroles
    - clusterrolebindings
  verbs: ["get", "list", "watch"]

# Allow read access to metrics
- apiGroups: ["metrics.k8s.io"]
  resources:
    - pods
    - nodes
  verbs: ["get", "list"]

# Allow read access to custom resources (CRDs)
- apiGroups: ["apiextensions.k8s.io"]
  resources:
    - customresourcedefinitions
  verbs: ["get", "list", "watch"]

# Allow exec into pods for debugging (but not delete)
- apiGroups: [""]
  resources:
    - pods/exec
    - pods/portforward
  verbs: ["create"]

# Allow read access to Helm releases (if using Helm)
- apiGroups: ["helm.cattle.io"]
  resources:
    - helmreleases
  verbs: ["get", "list", "watch"]

# Allow read access to Flux resources
- apiGroups: ["source.toolkit.fluxcd.io"]
  resources:
    - gitrepositories
    - helmrepositories
    - buckets
  verbs: ["get", "list", "watch"]

- apiGroups: ["kustomize.toolkit.fluxcd.io"]
  resources:
    - kustomizations
  verbs: ["get", "list", "watch"]

- apiGroups: ["helm.toolkit.fluxcd.io"]
  resources:
    - helmreleases
  verbs: ["get", "list", "watch"]

# Allow read access to monitoring resources (Prometheus, Grafana, etc.)
- apiGroups: ["monitoring.coreos.com"]
  resources:
    - prometheuses
    - alertmanagers
    - servicemonitors
    - podmonitors
    - prometheusrules
  verbs: ["get", "list", "watch"]

# Note: Explicitly NO delete, create, update, or patch verbs
# This ensures cursor user cannot modify or delete any resources
