apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-tunnel-credentials
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgCsiEVSsLrV9QKKpA2BnPDJT4WvNEXmyKkUPxhMDKbGCdNZXM5CHfZHodWKSDp0rf4qThHtNhrdRmyqa9ggp7tj0/kWOT2mplXLf05n4SB8DuutgmMRan8JrVp4GnEH58jJm2DMF6nySAoGKDKVGurW2JpAh0p5oSidY4YTR4T9JGUyo2KzzoOKk4p1zrCP9SvqTeM8ez35OuMGhxilcbspowgWKKFym5UAsU9ID+xct3HH6tl/1QR+rCIql0Kl8LwA5ZFmVrVB8zFAD87HXhXmgUMJtqq3x2Z0CD0V9BRAjMnDxLEjrIvcHkwVZCCAymA6XlXWoFm08DA1MpJa643iVuJ6/6FKoyhmt2v5ha+vXOMa85q9+9BMtuthp9i0t7f3uYgIo4hu2Ze19+f7N4um0qGJHiY8Mukrc5Ya6Zs7DVDoq2OSKRW3oJoB2ts08c/4iT16i6wEs+lDAUWjC4vYt7DjksSqzWyWZDf/1moUbWz9yQE/k5ESls/LAr+du8q8v1llwyeVC/Am8/npV7nyKcxn9EVUrqRJ++uys6NvPUcwiNXvvF9X2rR2dwgbk9A/P6Y3wIF2+giOFnHFctQBfZrLPFKyJowwUTMYGGCHwmcs3Xj+1KC4NaUGyW5OXSnIjMk7ndjDQYtI5CO6zmoiCw1lJ+YFXmzBQzdjfZq9zuzw4cVCIoxexF5DKcy84J+SY5uv74h+DYcdkiTESfbpY9ZztS67yNl4RDMXpOdFReo7Wdbc/F+KFWRYWJehJe+fugYwWghK+nefbrUsRROMqJoPrxfN2n+82kHxeb7lPFv3xy0CAAGE0KBCe9s9jfqQfvqBtjaKT7xol6mYlAUUpIfv8KE9LNgdzEyYNt0gfFN5FU0Xyh8iNWaXOUGkdA+ZgXRW+sDEeWkU38UucbvYqhafdD0JPTxb1xnsinaOflkonrNPRPBN
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-tunnel-credentials
      namespace: cloudflare-tunnel
    type: Opaque
---
