apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: agent-legacy
spec:
  encryptedData:
    .dockerconfigjson: AgAa12tklPqxte335xMFff6sDDRxo6KjAIYMbb2bqFVYyRrlxmRLX1gp843uqhcalTupjIF8bM1I7UDOoOJdqQ+KFT4j678oiJUFs0EQ+sQUVsmNISRoOSaOMPm+QbqFXkvRtIItt47GyFthu1WzzUHPIaRa2un7go91y3AkkVAgg5dXUxEU5TTOpsylHs5ndB0qdr/0JwudB3PDr1xq15lnXe16cZrl5szHidq2iRfOKHp8Ph4tytUTWKAwneonRrPDW6FgBLg8iMZBWFHJZB37rUFBofL+XJNfX9SWmju6756cZusMoYYZ5bjHPRiitXKsXdo8OUDQi44dVwDD0UxqhdleZgAsVXoRb/RuxyZBbG8hYow5q7nfpxhzETwuAx+T8T5bvOsP21Y2u9Jobap5r8a/qtIg8m5xQmClRecW21gT0miU/t0EMpM5trkNpwa1/XmX6XGOUdjrwByEJidNbBqBuG6xqBVgwOjTcE7vCL0fVF79XCEGTj6ibWzdPc29OHPHE3zTndxZ2tUhJNrQMDUTbQlRx6babhLhrWiTYoeLZxKmhnaPfAaQvnnr7Lfk2QdLHlIedjBpUs37XSle1G/7+bDoi4L1JZ9bXFPoIk7N/U37k4H9IohtHa2N+6AIB1Jsb9DxCc+XurB3m7Hpa1ORKpjucnI0f2Ika77ajvYJLmyYHN6wZj/95iJHuZ4Bvedt2d6z6ivJ33MpBg5ApXWwZBkcySLcuEFpWcskzoqlMvhLPfa9kBVN65k9tg3YFoklU4XaJBz5xwfBoQOhC0iMlIoxYWpY35JC7wVOhMXwdJKP4G+Zwt1LrI4hEjtZc/E7xK7Y65Z+hPGQ6bP07ak3Uos5rKGjxgWDePM7Mvo9xI8vxfUKzSamqGVEQXcvYYAnrPSV5bXsvQ9rrir2I5mVuEe2hvCZx6Xxc/EOuxnZdJ6ulEV6Fbc=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: agent-legacy
    type: kubernetes.io/dockerconfigjson