apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: bruno
spec:
  encryptedData:
    .dockerconfigjson: AgCnoqxnl0DFMwcajqyPS7O+I3Fj0IJ9ZYsBP4vAtJRBOuQLx5aluPwF3ITqEsJmbl8N3xmqz/17wGXBuNVVC29oC+iJ61BIS4ntefKj2yTESOGH9Rlqi75zv7lLFE3Od8+9UzVWACdFekHOgKCCqsU4HTQWfl5Ssu+luPFTQRqBQRfKUgy9OArL3qB2Wg+y25H6EZgtIcP/zasl1HbARZiBy2MNrSeQn1aEk6PS1SgW8Bxrd+sOW4Lnz+t1p0g4TbgzJjASDyu0hqGoar79dDP5A1W1SKPLNaybKw3VuTJmaNmom/BRzk2rBx+5xUIPhxzfdrXR6RGzMGDodvMxDZdupwLa7ojHJ3KpPCjHF027dIslBi/RJvx8OxhkwensBAO/E6rfFgfLeDMopnfiow/2IIR7oxI7kfp5C6fdSllXdAtVlELHSUs3069NLRLUtvhaADqHXOue0J5F9xE6iwsWJbl/sweMvs26Q1qkPPZIiPMFbt2ZKzhkCxKS071y1ve6xFwNuWRgGw+Mbe7rtZEtmiOMxvoKD0quzb13xt7+MI/ma2R8XyxBOVa9UXdOM962iAuF1Mbu4H6jtoOa/mJZIiDsB4ek+773YrnmM8ZLzhZTKDXAs8yFupTA/aMASPoG/EgZxSp1DcxUH9Gc6MVxbqAfdMtve77GNDKoyzg6OgbgpkaUaqCMznIhT25uOFkiWW2MuDczJoXP032XcCnyn3U9ZPzSaeOsm4qL2ekEHvJD42uJ0ouExR/NUsGyF8Kc1YewSeu0ErAQm8Z6uKiu5B4v5SFPf9wXfPt7+JvFy2utQRinyFbXIbqhtt2caBhQqRueAZbxl9ba
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: bruno
    type: kubernetes.io/dockerconfigjson
---
