
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
  finalizers:
    - finalizers.fluxcd.io
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: sealed-secrets
      version: 2.17.4
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
  values:
    fullnameOverride: sealed-secrets
    serviceAccount:
      create: true
      name: sealed-secrets
    rbac:
      create: true
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    # Ensure sealed-secrets survives destroy by preventing deletion
    # and maintaining the private key
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 0
    # Add persistence for the private key
    persistence:
      enabled: true
      storageClass: ""
      accessMode: ReadWriteOnce
      size: 1Gi
    tolerations: []
    nodeSelector: {}
    # Prevent accidental deletion
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
