---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: sealed-secrets
      version: 2.17.4
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
  values:
    fullnameOverride: sealed-secrets
    serviceAccount:
      create: true
      name: sealed-secrets
    rbac:
      create: true
    # resources:
    #   limits:
    #     cpu: 500m
    #     memory: 512Mi
    #   requests:
    #     cpu: 250m
    #     memory: 256Mi
    tolerations: []
    nodeSelector: {}
