---
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  version: "1.18.0"
  # Configuration based on notifi setup
  config:
    default-domain:
      example.com: ""
    # Enable metrics collection
    metrics:
      request-metrics-backend-destination: prometheus
    # Security settings
    security:
      system-internal-tls: enabled
  # Resource allocation similar to notifi
  resources:
    - container: controller
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 1000m
        memory: 1000Mi
    - container: webhook
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 1000m
        memory: 1000Mi
    - container: activator
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 1000m
        memory: 1000Mi
    - container: autoscaler
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 1000m
        memory: 1000Mi
