apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: loki-mcp
  namespace: flux-system

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - service-monitor.yaml
