apiVersion: v1
kind: Service
metadata:
  name: loki-mcp-server
  namespace: loki
  labels:
    app.kubernetes.io/name: loki-mcp
    app.kubernetes.io/component: mcp-server
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: mcp
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app.kubernetes.io/name: loki-mcp
    app.kubernetes.io/component: mcp-server
