apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: agent-legacy
  namespace: agent-legacy
  labels:
    app.kubernetes.io/name: agent-legacy
    app.kubernetes.io/component: ai-agent
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: agent-legacy
      app.kubernetes.io/component: ai-agent
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
